### ISSUE TITLE
sharedpreferences registration is not working.

### ISSUE THREAD

**Issue by usmanniqbal** [rekab-app/background_locator#101]
Hi I want to registered sharedpreferences but its not working here is my code in Application.kt

```
package kg.amanat.amanat

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.pathprovider.PathProviderPlugin
import io.flutter.view.FlutterMain
import rekab.app.background_locator.LocatorService

class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        LocatorService.setPluginRegistrant(this)
        FlutterMain.startInitialization(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin("io.flutter.plugins.sharedpreferences")) {
            PathProviderPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.sharedpreferences"))
        }
    }
}
```

When I try to access it it gives me this error `MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

Also in release mode `initCallback` is not being invoked

**Comment by gpibarra** [comment]
What version of flutter do you use?
Did you migrate the project to androidx?
Did you update the manifest file?

**Comment by ThiagoCortez81** [comment]
@usmanniqbal you registration of shared preferences is wrong!
You are doing: `PathProviderPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.sharedpreferences"))`
You need to overwrite it to `SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences"))`

Your error was that you was trying to register SharedPreferences Plugin using PathProvider plugin, this won't work.
Cheers.

**Comment by usmanniqbal** [comment]
My bad, Thanks @ThiagoCortez81.
