### ISSUE TITLE
Sqflite plug in exception

### ISSUE THREAD

**Issue by yarragollavijaykumar** [rekab-app/background_locator#108]
I am unable to access the database/file manager inside a callback in android platform
`Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel

**Comment by gpibarra** [comment]
[https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback](https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback)

**Comment by pradyumna67** [comment]
@gpibarra MissingPluginException is still coming after added LocatorService Plugin Registrant in Application class.

`public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        LocatorService.setPluginRegistrant(this);
        FlutterMain.startInitialization(this);
    }
    @Override
    public void registerWith(PluginRegistry registry) {
        if(registry.hasPlugin("com.tekartik.sqflite.SqflitePlugin")){
            SqflitePlugin.registerWith(registry.registrarFor("com.tekartik.sqflite.SqflitePlugin"));
        }
    }
}`

**Comment by gpibarra** [comment]
did you use the import in Application.kt? did you change the AndroidManifest.xml?

**Comment by pradyumna67** [comment]
@gpibarra yes, I did

**Comment by yarragollavijaykumar** [comment]
`public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback { @Override public void onCreate() { super.onCreate(); LocatorService.setPluginRegistrant(this); FlutterMain.startInitialization(this); } @Override public void registerWith(PluginRegistry registry) { if(registry.hasPlugin("com.tekartik.sqflite.SqflitePlugin")){ SqflitePlugin.registerWith(registry.registrarFor("com.tekartik.sqflite.SqflitePlugin")); } } }`

**Comment by ahmadkhedr** [comment]
"Invalidate Caches /restart" and try again

**Comment by mehdok** [comment]
It seems that problem is fixed, I'm closing it now but feel free to open it anytime;
