### ISSUE TITLE
BackgroundLocator.isRegisterLocationUpdate() returning false even if notification is showing.

### ISSUE THREAD

**Issue by TheEggHealer** [rekab-app/background_locator#109]
Hello! I'm having trouble connecting to the service after the app has been terminated by Android. If I let the app run in the background for about 15 minutes, the app is terminated by Android, however, the foreground service and location tracking is still operating. When I launch the app again, I want to know if the service is active but BackgroundLocator.isRegisterLocationUpdate() returns false. Has anybody else had the same issues? Is there anything I can do about this?

**Comment by mehdok** [comment]
Your problem should be fixed with PR [#120](https://github.com/rekab-app/background_locator/pull/120);
