### ISSUE TITLE
How to get is the service already running or not?

### ISSUE THREAD

**Issue by TheMisir** [rekab-app/background_locator#11]
I want to check if the service is running or not on app startup. Is there any exported function for checking that?

**Comment by gpibarra** [comment]
Just yesterday i made a pr of that
#10

**Comment by TheMisir** [comment]
Cool 👍

**Comment by mehdok** [comment]
[https://github.com/rekab-app/background_locator/pull/10](#10) merged.

**Comment by TheMisir** [comment]
@mehdok when you're planning to upgrade pub.dev package?
