### ISSUE TITLE
Can you support this plug-in without Google service framework? 

### ISSUE THREAD

**Issue by zy693415** [rekab-app/background_locator#111]
Can you support this plug-in without Google service framework? Thank you!

**Comment by mehdok** [comment]
Where I used `Google service framework` exactly? If you just point the location I can investigate more, but from what I know I didn't used `Google service framework`;

**Comment by fnicastri** [comment]
>Where I used Google service framework exactly?

basically everything from:
```
import com.google.android.gms.location.FusedLocationProviderClient
import com.google.android.gms.location.LocationRequest
import com.google.android.gms.location.LocationServices
```
is tied to `Google Services`.

I think it would be important to have a fallback to plain Android alternatives especially now that Huawei can't use Google stuff anymore.

[Plain Android API](https://developer.android.com/reference/android/location/package-summary.html)
[Google Service API](https://developers.google.com/android/reference/com/google/android/gms/location/package-summary)

**Comment by mehdok** [comment]
Oh I see, it would be a nice option to add, and having the options to use `plain android api` or `google service api`;

**Comment by mehdok** [comment]
@fnicastri @zy693415
Hello guys,
It would be nice if you could test that branch to see if everything is right or not;

**Comment by fnicastri** [comment]
@mehdok 
I think I'll have the time next week.

Thanks!

**Comment by zy693415** [comment]
@mehdok 
Thank you. I will test it sometime later. I wrote a corresponding plug-in for Android and have solved this problem.
In addition, in order to find the background positioning of ios terminal, the time interval setting is invalid and the positioning has been continuously, which consumes a lot of power.

**Comment by moovida** [comment]
Hi, I am also having users that can't work with google services. 
I would be able to test this but I need a bit of advise: to test this, can I just pull the master branch and it should work?

**Comment by mehdok** [comment]
@moovida Thank you for your help.

I have merged this with the master branch but didn't released a new version. 
- Download the master branch codes
- Put it in your app directory
- In the `pubspec.yaml` refer to this library as:

````lua
locator:
    path: ./background_locator
````

And you should be good to go.

**Comment by moovida** [comment]
great, I will create a package and send it to the person that has an /e/OS installed phone, It looks like these might be very happy about your fix. Thank you. 
I will report back as soon as I have an answer.

**Comment by moovida** [comment]
@mehdok , I got confirmation that it works 👍

**Comment by mehdok** [comment]
@moovida Thank you man, that was a great help;
