### ISSUE TITLE
[IOS] Location updates not coming in the background

### ISSUE THREAD

**Issue by rsbthebest** [rekab-app/background_locator#117]
Hi Team,

First of all thanks a lot for this plugin it's extremely useful! 

While it is working great for me on Android am facing some issue on IOS.

Here is what I have tried:

1. Copies the Example code given here
2. Gave all the needed permission in XCode
3. Tried running the app

Expectation:
I should be able to see location updates when 

- The screen in the foreground
- The App is minimized
- When the phone is locked 

Monitored the logs coming from the app and found that am only getting location updates when the app is in the foreground.

Am I missing anything here? How can I make sure the location updates are coming even when the phone is locked or the app is minimized?

Please let me know if any other details are needed!

Regards,
Rajdeep Barad

**Comment by mehdok** [comment]
What is your test device? Are you testing on real phone or simulator?

**Comment by mehul1891** [comment]
Mehdi, 

I support Rajdeep with this. We are testing on a real device - iPhone 6S with the latest iOS version installed. 

On the app settings on device: Background Refresh is ON, Location capture is set to "Always"
Xcode: background capabilities are enabled for location updates, background fetch and background processing 
Info.plist screenshot attached too.

Thanks,
Mehul

<img width="892" alt="image" src="https://user-images.githubusercontent.com/2579188/89728321-6700b980-da24-11ea-90ec-9b15fa088873.png">

**Comment by mehdok** [comment]
Try to simulate location update with [iSpoofer](https://www.ispoofer.com) and see if you can receive any location update or not. If not, try the example app and see if situation is the same or not;

**Comment by rsbthebest** [comment]
We have already tried the example app and it's the same behaviour there.

I will try the iSpoofer and would let you know the results but am not sure if that will help here.

**Comment by mehdok** [comment]
Any update?

**Comment by mehdok** [comment]
Closed the issue due inactivity, feel free to open it anytime;
