### ISSUE TITLE
Pub get throws error asking project to be upgraded

### ISSUE THREAD

**Issue by hemant456** [rekab-app/background_locator#122]
The plugin `background_locator` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

I don't want to migrate my whole project at the moment. Is there a simple workaround? I was really excited about giving this plugin a try but this bumped me up.

**Comment by mehdok** [comment]
I don't think there is a way to do that, but if you found any solution please share it with others;

**Comment by mehdok** [comment]
Cosed the issue due to inactivity, feel free to open it anytime;
