### ISSUE TITLE
Crashes on new Flutter update.

### ISSUE THREAD

**Issue by DiegoFHG** [rekab-app/background_locator#129]
This plugin worked fine, until the new Flutter update. Now it throws this error, crashing the app:

E/AndroidRuntime( 1281): java.lang.RuntimeException: Unable to create service rekab.app.background_locator.LocatorService: java.lang.IllegalStateException: FlutterCall
E/AndroidRuntime( 1281):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4204)
E/AndroidRuntime( 1281):        at android.app.ActivityThread.access$1500(ActivityThread.java:237)
E/AndroidRuntime( 1281):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
E/AndroidRuntime( 1281):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 1281):        at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 1281):        at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 1281):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1281):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 1281):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 1281): Caused by: java.lang.IllegalStateException: FlutterCallbackInformati…formation(callbackHandle) must not be null
E/AndroidRuntime( 1281):        at rekab.app.background_locator.LocatorService.a(:81)
E/AndroidRuntime( 1281):        at rekab.app.background_locator.LocatorService.onCreate(:69)
E/AndroidRuntime( 1281):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4192)
E/AndroidRuntime( 1281):        ... 8 more

I'm using the latest version of this plugin.

**Comment by mehdok** [comment]
@DiegoFHG I just upgraded the flutter to the latest version, then I tried to install the example app and it gave me an error. ‌But this [answer](https://github.com/flutter/flutter/issues/59645#issuecomment-645240371) helped me fix that. After that I ran the example normally and everything seems ok without any crash;

**Comment by DiegoFHG** [comment]
Seems that it doesn't crashes on a real Android device. I'll try on the iOS simulator.

**Comment by mehdok** [comment]
Closed the issue since the problem is only exists on somulator. Fell free to open it anytime;

**Comment by Jparrgam** [comment]
Hi, @mehdok @gpibarra Do you have any idea of this crash, it is happening to me and I am running on a real device

**Comment by Jparrgam** [comment]
@DiegoFHG hey bro, sabes como ajustarlo, tengo muchos bugs sobre esto si sabes algo por fa seria de gran ayuda

**Comment by mehdok** [comment]
Hi @Jparrgam 

What is your flutter version?

**Comment by Jparrgam** [comment]
> Hi @Jparrgam
> 
> What is your flutter version?

@mehdok 

`Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (3 months ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0
`

**Comment by bayuly94** [comment]
same error
