### ISSUE TITLE
database and callback

### ISSUE THREAD

**Issue by HeikkiK** [rekab-app/background_locator#131]
I tried to save coordinates into database in callback but I couldn't. When I tried to pass database through initDataCallback as a parameter it just doesn't do anything anymore, just stop doing anything. It freezes... When I try to open database in initCallback it doesn't finish database initialization but jumps out from the initialization code before end. 
Everything works well when running from anywhere else than callbacks. I have used "wait" and "Future" in database initialization functions (open).  I also downloaded latest version which was published on Wednesday but it didn't help.
I haven't use callbacks too much before this case so it could be that I don't know something important about those. 
But if someone could tell what's wrong and help me with this, I would be pleased. :)

**Comment by mehdok** [comment]
Did you followed [Use other plugins in callback](https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback#use-other-plugins-in-callback) ?

**Comment by HeikkiK** [comment]
What does that code actually do? Is it used somewhere in example?

**Comment by mehdok** [comment]
The code just ensure that your plugin is initialized in the background. We used `PathProvider` plugin in the background. You can find the codes in example;

**Comment by HeikkiK** [comment]
Do I have to modify that file or just add is as it is? I added it but didn't change my app behavior. Because I have jumped directly from MS world into flutter, not so familiar with android dev yet.
App runs callback when location is changed even when app is not running but when opening database it never completes opening because it jumps out from that method and continues callback code. Anyway, although I get location correctly it is not saved...

**Comment by HeikkiK** [comment]
So if there is someone who can get sqflite saving works in callback please let me know how.

**Comment by mehdok** [comment]
All you need to do is to modify the code and change the package name according to your needs. In this case just find the package name of the database library and replace it with the `PathProvider` package name;

**Comment by HeikkiK** [comment]
ok I finally got it work. Thank you!  👍

**Comment by HeikkiK** [comment]
btw, I have database open function in initcallback and usually it works ok, but when registerLocationUpdate is just been executed then database isn't yet open when callback already runs and in my case start location isn't saved. Ofcourse I can do code to check that db is open before saving first location etc. But should callback wait that initcallback is executed before it executes?

**Comment by mehdok** [comment]
Short answer NO, I think it is more convenient to do all of the database operation (include opening and saving ....) in the `callback` function; `callback` is a separate piece of code that would be executed every time;
