### ISSUE TITLE
[Question] Change distance and interval in callback

### ISSUE THREAD

**Issue by miguel-cons** [rekab-app/background_locator#132]
Hello, I have a question, it's possible to change the distance and / or the inteval in the callback? For example, suppose that this parameters are received from a database, so the callback method check the database and if any of this parameters have been changed, it update them and restart the process or automatically the BackgroundLocator apply them.

Thanks so much.

P.S. Great plugin, my congrats!!

**Comment by mehdok** [comment]
Hi Miguel,

Right now we don't have this ability;

**Comment by miguel-cons** [comment]
Ok, thanks so much.
