### ISSUE TITLE
Test app & implementation crash on stop

### ISSUE THREAD

**Issue by madatr** [rekab-app/background_locator#134]
Hi,
Firstly, thank you for developing and maintaining such a useful app.
I have implemented your app within mine, sometimes when trying to stop the location service (onStop()) the application crashes, it is more noticeable/recreatable when the location update interval is shorter.

I thought the the issue is from my implementation, but testing the example app results in the same error, to recreate start the location service and once a location fix is acquired stop the service, it does not always do it so multiple attempts may be required.

I believe the issue maybe from the notification handler, I have searched your app for a function to cancel the notification before stopping the location service but there is none. This issue maybe related to #121.

Anyway, here is the debug console output:

`I/flutter (27263): 1 location in dart: LocationDto{latitude: XX.XXXXXXX, longitude: XX.XXXXXXX, accuracy: 7.75, altitude: 566.6, speed: 0.05126497521996498, speedAccuracy: 0.0, heading: 3.5622213187015694e-13, time: 1599297358000.0, isMocked: false}

I/flutter (27263): ***********Dispose callback handler

I/flutter (27263): 2

V/jhw     (27263): call Intent.migrateExtraStreamToClipData(1)
D/AndroidRuntime(27263): Shutting down VM

E/AndroidRuntime(27263): FATAL EXCEPTION: main

E/AndroidRuntime(27263): Process: rekab.app.background_locator_example, PID: 27263

E/AndroidRuntime(27263): java.lang.RuntimeException: Unable to start service rekab.app.background_locator.IsolateHolderService@32fb58b with Intent { act=UPDATE_NOTIFICATION cmp=rekab.app.background_locator_example/rekab.app.background_locator.IsolateHolderService (has extras) }: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=app.rekab/locator_plugin pri=1 contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 vis=PRIVATE)

E/AndroidRuntime(27263): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3744)
E/AndroidRuntime(27263): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime(27263): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1880)
E/AndroidRuntime(27263): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27263): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(27263): 	at android.app.ActivityThread.main(ActivityThread.java:6861)
E/AndroidRuntime(27263): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27263): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
E/AndroidRuntime(27263): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(27263): Caused by: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=app.rekab/locator_plugin pri=1 contentView=null vibrate=null sound=null defaults=0x0 flags=0xa color=0x00000000 vis=PRIVATE)
E/AndroidRuntime(27263): 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:320)
E/AndroidRuntime(27263): 	at android.app.NotificationManager.notify(NotificationManager.java:289)
E/AndroidRuntime(27263): 	at android.app.NotificationManager.notify(NotificationManager.java:273)
E/AndroidRuntime(27263): 	at rekab.app.background_locator.IsolateHolderService.updateNotification(IsolateHolderService.kt:233)
E/AndroidRuntime(27263): 	at rekab.app.background_locator.IsolateHolderService.onStartCommand(IsolateHolderService.kt:182)
E/AndroidRuntime(27263): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3718)
E/AndroidRuntime(27263): 	... 8 more
I/zygote  (27263): Do full code cache collection, code=126KB, data=114KB
I/zygote  (27263): After code cache collection, code=119KB, data=80KB
Lost connection to device.
Exited (sigterm)`

Please help, I am able to provide any additional info if need be.

Thanks,

**Comment by madatr** [comment]
Ok, i have fixed it.
The issue is related to the notification update part, it seems that even after calling onStop() the isolate keeps continues the current run or at least that's what i believe because the crash has a delay.

I tracked the path of the program up until the crash and it leads to the update notification part (updateUI()).

I am not entirely sure which code fixed it because i've added multiple checks that check if (isRunning) true => proceed in the notification update, if not then do nothing.

This is most likely the one that has done it:


`port.listen(
      (dynamic data) async {
        **await updateUI(data);**
      },
    );`

====>

port.listen(
      (dynamic data) async {
        **if (data != null && isRunning) {**
          await updateUI(data);
        } else {
          return;
        }
      },
    );

**Comment by mehdok** [comment]
Hi @madatr 
Thank you for opening an issue and thank you for answering it :).
Please close the issue if it is solved;

**Comment by madatr** [comment]
No worries ;)
