### ISSUE TITLE
Android only returns every few minutes

### ISSUE THREAD

**Issue by ndhbr** [rekab-app/background_locator#138]
Hello,

thanks for the plugin.

I wanted to ask if it is normal that when the Android version is running in the background it sends a location only every few minutes? I have attached a screenshot. If I keep the emulator open everything works perfectly. If I turn off the screen from the emulator and wait for a while I see that only every few minutes a location is requested.

So I cannot deliver the product. What can I do about it? As I understand the Android documentation, background services are only allowed to check the location a few times per hour. But because of the notification the service is a "Foreground Service", isn't it? But shouldn't I be able to access the location as often as I have the display on?

How do all those jogging and fitness apps make it so good?

With iOS, however, it works perfectly in the background.

![android_emulator_api_29](https://user-images.githubusercontent.com/13482230/93189541-8afd9c00-f742-11ea-982f-e04804485220.png)

**Comment by mehdok** [comment]
Hi @ndhbr 
Thank you for opening an issue.

Short answer No it's not normal.

I wouldn't surprise if you had this problem on iOS. But in Android sending location data in every `interval` should be guaranteed.

1. What is your `interval` in Plugin Setting ?
2. Does this happens only when app is in background?
3. Does sending location data getting delayed from the moment you put app in background or it is normal for a few moment?
4. Please provide Any additional data (logs, codes, possible scenario) that could help with identifying the problem.

**Comment by ndhbr** [comment]
> I wouldn't surprise if you had this problem on iOS. But in Android sending location data in every `interval` should be guaranteed.

I thought so too, but with iOS it works fine.

> 1. What is your `interval` in Plugin Setting ?

I set the interval to 3.

> 2. Does this happens only when app is in background?

Yes, in the foreground it works as desired.

> 3. Does sending location data getting delayed from the moment you put app in background or it is normal for a few moment?

When I minimize the app or turn off the screen the location still works normally for a while. I see in the output that it still gets about 50-60 locations.

From then on the output does not output anything. And then it doesn't output anything anymore. As soon as I go back into the app I see that only every few kilometers a location is retrieved.

> 4. Please provide Any additional data (logs, codes, possible scenario) that could help with identifying the problem.
I also use the Path Provider plugin, as in the example. I append each captured position byte-wise to a binary file. In my "updateUI" method I then read the file from the required point and draw lines to the newly acquired points. This works very well under iOS and under Android unfortunately only in the foreground.

Here is a small part of my log. One record has 20 bytes. So normally the offset jumps up 20 bytes when it gets a position. Here it stopped writing to the console after 1140 bytes (1140 / 20 = 57 locations). Since my interval is 3 seconds the exact location stopped after ~2.9 minutes.

```
I/flutter (19721): Read file from byte 960. Got 1 new positions
I/flutter (19721): updateUI: 48.80933380126953, 11.795769691467285 - Time: 1600172064768.0
I/flutter (19721): Read file from byte 980. Got 1 new positions
I/flutter (19721): updateUI: 48.809715270996094, 11.796320915222168 - Time: 1600172064768.0
I/flutter (19721): Read file from byte 1000. Got 1 new positions
I/flutter (19721): updateUI: 48.8098030090332, 11.797342300415039 - Time: 1600172064768.0
I/flutter (19721): NEW MAX SPEED: old: 35.381771087646484 new: 35.78877258300781
I/flutter (19721): Read file from byte 1020. Got 1 new positions
I/flutter (19721): updateUI: 48.80979537963867, 11.798701286315918 - Time: 1600172064768.0
I/flutter (19721): Read file from byte 1040. Got 1 new positions
I/flutter (19721): updateUI: 48.80982971191406, 11.799582481384277 - Time: 1600172064768.0
I/flutter (19721): Read file from byte 1060. Got 1 new positions
I/flutter (19721): updateUI: 48.80989074707031, 11.800590515136719 - Time: 1600172064768.0
I/flutter (19721): Read file from byte 1080. Got 1 new positions
I/flutter (19721): updateUI: 48.809940338134766, 11.801417350769043 - Time: 1600172064768.0
I/flutter (19721): Read file from byte 1100. Got 1 new positions
I/flutter (19721): updateUI: 48.80998611450195, 11.802240371704102 - Time: 1600172064768.0
I/flutter (19721): Read file from byte 1120. Got 1 new positions
I/flutter (19721): updateUI: 48.81004333496094, 11.803336143493652 - Time: 1600172064768.0
I/flutter (19721): Read file from byte 1140. Got 1 new positions
I/flutter (19721): updateUI: 48.80995559692383, 11.804574966430664 - Time: 1600172064768.0
```

Here are two comparison pictures. The big jump was when the emulator was off and when I turned the emulator on again you can see that the locations became accurate again (the curve).

https://imgur.com/a/lXAhRdJ

I uploaded the pictures to Imgur because I didn't know how to collapse pictures in markdown, sorry.

Thanks in advance!
Andreas

**Comment by gpibarra** [comment]
"UpdateUI", does it mean that you are receiving the location in callbackBackground and sending it to the mainApp in foreground through the port?

**Comment by ndhbr** [comment]
Yes, I do it like in the example project

```
    port.listen((dynamic data) async {
      await updateUI(data);
    });
```

**Comment by ndhbr** [comment]
> Try to log inside callback function.

I'll try it out.

> It is not recommended to update UI from backgroud.

That was not my intention either. This is now my callback-function. 

```
  static Future<void> callback(LocationDto locationDto) async {
    final SendPort send = IsolateNameServer.lookupPortByName(ISOLATE_NAME);

    print('${locationDto.latitude}, ${locationDto.longitude}');

    await RideFileManager.appendPosition(
        RideRoutePosition.fromLocationDto(locationDto));

    send?.send(locationDto);
  }
```

I thought that the port.listen(...) function is only called when the application is in the foreground.

**Comment by ndhbr** [comment]
> Try to log inside callback function.

I have now tested this. The logging in the callback function stops at the same time as the logging of the port.listen(..) function in the UI.

**Comment by ndhbr** [comment]
Soooo. After long debugging and reading hex dumps I know what it is. The callback stops extending the file at some point. But I have absolutely no idea what the reason is. Does Android have a limit that says "stop writing to the file so often"?

I have attached a log example. The logs come from the callback. The first and last data were in the file, nothing in between. All others were skipped.

```
I/flutter (26587): CALLBACK: 48.8090714, 11.9170985, Timestamp: 1600184297000.0 <-- that was written to the File
I/flutter (26587): CALLBACK: 48.809198, 11.9179886, Timestamp: 1600184301000.0
I/flutter (26587): CALLBACK: 48.8093136, 11.9187521, Timestamp: 1600184304000.0
I/flutter (26587): CALLBACK: 48.8094388, 11.9195373, Timestamp: 1600184308000.0
I/flutter (26587): CALLBACK: 48.8095733, 11.9202153, Timestamp: 1600184311000.0
I/flutter (26587): CALLBACK: 48.8097615, 11.9210426, Timestamp: 1600184315000.0
I/flutter (26587): CALLBACK: 48.8099431, 11.9219578, Timestamp: 1600184319000.0
I/flutter (26587): CALLBACK: 48.8101067, 11.9227692, Timestamp: 1600184322000.0
I/flutter (26587): CALLBACK: 48.8102836, 11.9234704, Timestamp: 1600184326000.0
I/flutter (26587): CALLBACK: 48.8105476, 11.9244419, Timestamp: 1600184330000.0
I/flutter (26587): CALLBACK: 48.8107405, 11.9251772, Timestamp: 1600184333000.0
I/flutter (26587): CALLBACK: 48.8109174, 11.9259199, Timestamp: 1600184337000.0
I/flutter (26587): CALLBACK: 48.8111311, 11.9269285, Timestamp: 1600184340000.0
I/flutter (26587): CALLBACK: 48.8112907, 11.9280647, Timestamp: 1600184344000.0
I/flutter (26587): CALLBACK: 48.8113866, 11.9292069, Timestamp: 1600184348000.0
I/flutter (26587): CALLBACK: 48.8114384, 11.9300426, Timestamp: 1600184352000.0
I/flutter (26587): CALLBACK: 48.8115285, 11.9309131, Timestamp: 1600184355000.0
I/flutter (26587): CALLBACK: 48.8116547, 11.9316685, Timestamp: 1600184359000.0
I/flutter (26587): CALLBACK: 48.8118252, 11.9323755, Timestamp: 1600184362000.0
I/flutter (26587): CALLBACK: 48.8121118, 11.9331026, Timestamp: 1600184366000.0
I/flutter (26587): CALLBACK: 48.8123913, 11.9337781, Timestamp: 1600184369000.0
I/flutter (26587): CALLBACK: 48.8127386, 11.9344301, Timestamp: 1600184373000.0
I/flutter (26587): CALLBACK: 48.8130898, 11.9351525, Timestamp: 1600184377000.0
I/flutter (26587): CALLBACK: 48.8134637, 11.93593, Timestamp: 1600184380000.0 <-- that was written to the File
```

With these methods I write to my file.

```
  /// Appends position to ride file
  static Future<void> appendPosition(RideRoutePosition rideLocationData) async {
    final file = await _getRideFile();
    final IOSink sink = file.openWrite(mode: FileMode.append);
    sink.add(rideLocationData.toByteList());
    await sink.close();
  }
...
  /// Converts object to byte list for IOSink
  Uint8List toByteList() {
    final ByteData data = ByteData(LOCATION_OBJECT_BYTE_SIZE);

    data.setFloat32(0, altitude);
    data.setFloat32(4, speed);
    data.setFloat64(8, time);
    data.setFloat32(16, latitude);
    data.setFloat32(20, longitude);

    return data.buffer.asUint8List();
  }
```

Please tell me you have an idea what this is all about. I'm starting to freak out... 😩

**Comment by ndhbr** [comment]
@mehdok @gpibarra do you have any idea? 🥺

I'm still stuck on the problem that the callback gets the locations, but the file sometime when the app is in the background is only written every few minutes. I tried to implement a temporary buffer that only writes all 10 locations to the file. Does not change anything.

**Comment by ndhbr** [comment]
Even if you are obviously not interested: The Example App does not work either and has the same problem. So the plugin is simply unusable.

![image](https://user-images.githubusercontent.com/13482230/93661845-7cbdc180-fa5b-11ea-9c07-197aaacb668e.png)

**Comment by mehdok** [comment]
Hi @ndhbr,
And thank you for your patient .

You should know that  me and other contributors  here have a daily job to do and even a life to live. So it is normal that answering or fixing a problem gets delayed. We even had issue which is fixed 2 month after reporting.

On the other hand, the licence  of the library explicitly says you can use the plugin freely, you can distribute it freely, you can modify it freely, but we do not guarantee anything.

At the end I would be more than happy to see a PR from you fixing this issue.

Good luck my friend.

**Comment by ndhbr** [comment]
I understand that you cannot invest endless time in this project. A small confirmation that you will look at it sometime would have been good anyway.

I urgently need this for a product, so I switched to the paid version of Transistorsoft.
