### ISSUE TITLE
Returned data to include accuracy

### ISSUE THREAD

**Issue by afung2468** [rekab-app/background_locator#140]
This package returns latitude and longitude. Can you include accuracy in the data returned? For example, if the accuracy is +/- 1000 meters then accuracy should be 1000. This should help to filter out the "spikes".

**Comment by mehdok** [comment]
Hi @afung2468 
Thank you for opening an issue.

I believe we have [accuracy](https://github.com/rekab-app/background_locator/blob/e98e292881a35b248891dce3ebbe64194b70c836/lib/location_dto.dart#L8) in the data model;

**Comment by afung2468** [comment]
Thanks for the quick reply. The accuracy data helps a lot in determining if the location reading is useful. Thanks.
