### ISSUE TITLE
Error when trying to update notification text from callback

### ISSUE THREAD

**Issue by HeikkiK** [rekab-app/background_locator#150]
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method LocatorPlugin.updateNotification on channel app.rekab/locator_plugin))

Should it be possible to update notification text when app is closed? Tested in android emulator and phone.

**Comment by mehdok** [comment]
Hi @HeikkiK 
Thank you for reporting an issue;

Yes, I believe you are trying to update notification text from `callback` function, is that right?

**Comment by HeikkiK** [comment]
Yes.

**Comment by mehdok** [comment]
Right now it is not possible to do that, But I think we have an open `PR` about this issue;

**Comment by HeikkiK** [comment]
Any news when update is coming?

**Comment by mehdok** [comment]
Sadly no, But if you are interested in help you can clone #137 and let me know if it's working for you;
