### ISSUE TITLE
Battery usage details and gps settings permission by default 

### ISSUE THREAD

**Issue by newbieflutter** [rekab-app/background_locator#151]
Hi,
    You have created a great plugin. Just some minor issue now what happens is that I on my app then I remove it from the memory meaning it goes to the background it keep working for some time. Then the phone is gone to sleep meaning the screen is off. Then say after 15 minutes I check no more updates. Then what I did was I choose the battery usage details and set is to be power-intensive prompt enable. Then in the app launch I set it to be manage manually and again in it the settings I enable it to run in background. So what I am asking is it possible to enable all this by default. Also is it possible to stop the user from closing the gps access once the app is running cause if they close the gps access then whole app will stop working though

**Comment by mehdok** [comment]
Hi @newbieflutter 
Thank you for opening an issue;

I don't think what you want is possible, but nothing is impossible in this world:) I would be more than happy to hear from you if you found any programmatic solution for this;
