### ISSUE TITLE
Can this plugin be used in production apps? 

### ISSUE THREAD

**Issue by smolugu** [rekab-app/background_locator#153]
Hi,

we need to fetch user location when the app is in the background. just to know the current location, nothing more.
Can this plugin be used in production apps? 

Regards,
Shyam

**Comment by mehdok** [comment]
Hi @smolugu 
Thank you for opening an issue.

I'm not sure what is your question :)

What do you mean by "nothing more"? Do you just want *one* location? then you can start the plugin get your location and stop it;

**Comment by smolugu** [comment]
Hi, this is not an issue. I just need clarification.

We need to listen to location changes in the background and update our database every 5 to 10 minutes.

Just want to know if this plugin can be used in production for my use case and if there are any limitations. I see people reporting issues like app crashing upon restart etc.,

Thank you,
Shyam

**Comment by mehdok** [comment]
We are using this plugin within our app **REKAB** without any specific problem. But as you saw some people have crashes and other problems with the plugin. I will try to address all of them but my timetable is very limited. So as the license says you can use this plugin where ever you want, but there is no guarantee. If you want something with guarantee and support you can use *Transistor software* plugin.

**Comment by smolugu** [comment]
ok. Thank you for your inputs. We will try this plugin and see how things go and then go with the Transistor software plugin if needed.

**Comment by mehdok** [comment]
Please share you experience after that, I would be more than happy to hear from you;

**Comment by smolugu** [comment]
Sure.

I am getting an error during the setup. can you please help?

<img width="639" alt="Screen Shot 2020-10-15 at 5 32 48 PM" src="https://user-images.githubusercontent.com/8217755/96120808-becc0d00-0f0c-11eb-94ed-a83ff43f36b2.png">

**Comment by mehdok** [comment]
This is related to Xcode profiling, as the error says connect an iOS device and let Xcode do what he want;

**Comment by smolugu** [comment]
hi.. I am closing this. have created a new issue. please look into it.

Thank you,
Shyam

**Comment by smolugu** [comment]
@mehdok hi, the plugin works fine on Android.

but getting this error on iOS

`Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 50940`

have tried workmanager plugin too. it works on android but gives same error on iOS.

Some thing to do with settings in AppDelegate.swift file.

really need to fix this at the earliest. please see if you can comment of possible reasons

regards,
Shyam
