### ISSUE TITLE
iOS other plugins in callback fail?

### ISSUE THREAD

**Issue by shaunramsey** [rekab-app/background_locator#158]
The code provided here: https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback

I'm trying to link in a background locator using cloud_firestore. The app uses firestore in many other locations.

On iOS only, after initPlatformState (BackgroundLocator.initialize in specific), my future firestore queries get hung in Waiting connection state.

There are no visible errors otherwise and the code works fine on Android.

**Comment by Shub-29** [comment]
so the default plugin is working in ios without using cloud firestore?

**Comment by bhanuka96** [comment]
same issue

**Comment by bhanuka96** [comment]
@mehdok Firebase firestore stream data is not listening. (data not return). 

Firestore stream is working after removing these two

`await BackgroundLocator.initialize();`
`IsolateNameServer.registerPortWithName(port.sendPort, LocationServiceRepository.isolateName);`

**Comment by mehdok** [comment]
Hi Guys,
Thank you for opening an issue and sorry that I have missed your posts;

@bhanuka96 
Please share a working example of what you are referring to, so I can check it out;

**Comment by bhanuka96** [comment]
@mehdok I updated my code

**Comment by bhanuka96** [comment]
```
 @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _bls.startLocationService();
    locationSubscription = _bls.port.listen(backgroundLocPort); //working, data is return
   connectionSubscription = _connectivityService.connectionStream.listen(connectionStream); //working, data is return
   oneSubscription = db.getUser(uid).listen(getUser); //not working, data is not return
```

**Comment by mehdok** [comment]
@bhanuka96 
Thank you for sharing the code, it's really hard to tell what's wrong just by having this chunk of code. It would be very helpful if you could create a simple working example with this scenario.

**Comment by bhanuka96** [comment]
@mehdok Sorry my mistake. not ` IsolateNameServer.registerPortWithName`. I remoe this `await BackgroundLocator.initialize();`, now stream listen is working. I think I want to register firestore callback, like this https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback, how do I find firestore callback?

**Comment by johnnypramadya** [comment]
Same issue, get exception on ios only.
throw MissingPluginException('No implementation found for method $method on channel $name').
Call this after BackgroundLocator.initialize()  :
await TwilioProgrammableChat._methodChannel.invokeMethod('Channel#join', {'channelSid': _sid});

But its normal if call that before BackgroundLocator.initialize(), any solution please ?

**Comment by mehdok** [comment]
@bhanuka96 
@johnnypramadya 

You need to find plugin package name, look into one of it's android file and you can see it; they are usually the same for android and iOS, but it might be different;

**Comment by bhanuka96** [comment]
@mehdok Then register like this. Am I right?

```
    func registerOtherPlugins() {
        if !hasPlugin("FLTFirebaseFirestorePlugin") {//but this not working, may be package name is incorrect
            FLTFirebaseFirestorePlugin
                .register(with: registrar(forPlugin: "FLTFirebaseFirestorePlugin")! )
        }
    }
```

**Comment by mehdok** [comment]
Yes the package is wrong, the right one is `io.flutter.plugins.firebase.cloudfirestore`. You can see it [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/android/build.gradle).

**Comment by bhanuka96** [comment]
@mehdok sorry, no luck

if !hasPlugin("io.flutter.plugins.firebase.cloudfirestore") {
            FLTFirebaseFirestorePlugin
                .register(with: registrar(forPlugin: "io.flutter.plugins.firebase.cloudfirestore") as! FlutterPluginRegistrar)
        }

**Comment by Shub-29** [comment]
I dont know how this plugin is working in ios.  When I am running the example code in simulator, i am getting the location just for one time.

**Comment by mehdok** [comment]
@bhanuka96 

Does it work?

**Comment by mehdok** [comment]
@Shub-29 

Please open another issue, I don't think this is related to this issue;

**Comment by bhanuka96** [comment]
okay

**Comment by mehdok** [comment]
Okey? I have asked if this new code works for you or  not? :)

**Comment by johnnypramadya** [comment]
> @bhanuka96
> @johnnypramadya
> 
> You need to find plugin package name, look into one of it's android file and you can see it; they are usually the same for android and iOS, but it might be different;

still not working, stream not working after this 
`static Future<void> initialize() async {
    final CallbackHandle callback =
        PluginUtilities.getCallbackHandle(callbackDispatcher);
    await _channel.invokeMethod(Keys.METHOD_PLUGIN_INITIALIZE_SERVICE,
        {Keys.ARG_CALLBACK_DISPATCHER: callback.toRawHandle()});
  }`

the question is how to uninitialized that ?

**Comment by mehdok** [comment]
@johnnypramadya 

Please look into #167

**Comment by johnnypramadya** [comment]
> @johnnypramadya
> 
> Please look into #167

The stream still doesnt work

`import UIKit
import Flutter
import GoogleMaps
import background_locator
import twilio_programmable_chat
import simple_auth_flutter

func registerPlugins(registry: FlutterPluginRegistry) -> () {
    if (!registry.hasPlugin("BackgroundLocatorPlugin")) {
        GeneratedPluginRegistrant.register(with: registry)
    } 
}

@UIApplicationMain
/// <#Description#>
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    UIApplication.shared.setMinimumBackgroundFetchInterval(TimeInterval(60*15))
    let notificationCenter = UNUserNotificationCenter.current()
    notificationCenter.delegate = self
    GeneratedPluginRegistrant.register(with: self)
    BackgroundLocatorPlugin.setPluginRegistrantCallback(registerPlugins)
    registerOtherPlugins()
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
    
        func registerOtherPlugins() {
                if !hasPlugin("twilio.flutter.twilio_programmable_chat") {
                    TwilioProgrammableChatPlugin
                        .register(with: registrar(forPlugin: "twilio.flutter.twilio_programmable_chat") as! FlutterPluginRegistrar)
                }
        }`

**Comment by mehdok** [comment]
This problem is related to cloud_firestore. Please look at #167 for the solution;
