### ISSUE TITLE
Android application crashed :FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by saravananmnm** [rekab-app/background_locator#161]
java.lang.RuntimeException: Unable to create service rekab.app.background_locator.LocatorService: java.lang.IllegalStateException: Plugin key io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin is already in use
E/AndroidRuntime(11250): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3965)
E/AndroidRuntime(11250): 	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
E/AndroidRuntime(11250): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
E/AndroidRuntime(11250): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(11250): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(11250): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(11250): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11250): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(11250): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(11250): Caused by: java.lang.IllegalStateException: Plugin key io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin is already in use

**Comment by saravananmnm** [comment]
`

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;
import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin;
import com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin;
import io.flutter.plugins.pathprovider.PathProviderPlugin;
import rekab.app.background_locator.LocatorService;

public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {

    @Override
    public void onCreate() {
        super.onCreate();
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
        //BackgroundFetchPlugin.setPluginRegistrant(this);
        LocatorService.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        // I've only had to add this line to make it work
        FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
        FlutterLocalNotificationsPlugin.registerWith(registry.registrarFor("com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin"));
        //BackgroundFetchPlugin.registerWith(registry.registrarFor("com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin"));
        PathProviderPlugin.registerWith(registry.registrarFor("io.flutter.plugins.pathprovider"));

    }
}
`

**Comment by sanidhyaagrawal** [comment]
Did you manage to resolve this? I am facing the same :/

**Comment by mehdok** [comment]
Hi @sanidhyaagrawal 
Thank you for opening an issue.

> ava.lang.IllegalStateException: Plugin key io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin is already in use

I think you need to do a check inside `registerWith` to see whether the `FirebaseMEssagingPlugin` is registered or not, then register it;
