### ISSUE TITLE
GPS Consideration!

### ISSUE THREAD

**Issue by slemankfa** [rekab-app/background_locator#164]
Hi ^^. 
it's a question more than an issue. 
in my case, I send location data to my server. the package is working fine when I use (LocationAccuracy.NAVIGATION)  and the GPS is turned on but it seems the callback is stopped and bind when the pgs is off, which is normal as I understand. 

To be more specific, my question is can I do anything to retrieve empty data, for instance, latitude = 0, longitude = 0  inside LocationDto in case if the GPS was off !!
I tried to change LocationAccuracy to low but still the same !!  and I already checked almost all issue section but I didn't find what I want. 

The package is really amazing and you are doing a great job!  

I am looking forward to hearing from you. 
cheers!.

**Comment by mehdok** [comment]
Hi @slemankfa 
Thank you for opening an issue.

I don't think that there is any way to do that inside the plugin. If you really need this feature you can listen to GPS status (via another plugin) and when it went off you can start a timer and send empty data to server.

**Comment by slemankfa** [comment]
Hi @mehdok  
Thank you for your replay. 
The Idea is the callback method never called when the GPS is off.  
is there any way to call it even if the GPS  is off!!  
I already forked the package and clone it and I have been tracking it since almost an hour to understand how it's done and another issue that I don't have any clue almost with Kotlin. 

Do you have any suggestions would help me !!

**Comment by mehdok** [comment]
The plugin completely depends on the GPS service to call the callback. So when the GPS is off there wouldn't be any new location and the callback won't get call at all.

As you can see [here](https://github.com/rekab-app/background_locator/blob/e98e292881a35b248891dce3ebbe64194b70c836/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt#L118) I just register for new location update and with each location update a `PendingIntent` gets called and it eventually trigger the callback in flutter code.

**Comment by slemankfa** [comment]
I got it. 
Thanks for your explanation everything is clear for me now. 
about your suggestion in the first replay, I can't do another sticky foreground service I think it's out of the box for me when the app is closed. 
however, I will keep looking for a solution. 
thanks again for this work I hope you will put this feature in your consideration in the near future ^^.

**Comment by mehdok** [comment]
It would be nice to have this feature in the plugin, I look forward to hear from you if you found any solution.

**Comment by slemankfa** [comment]
I strongly believe, it will be a great feature too. 

I will do my best and notify you if I get any update as soon as possible. 
Cheers!

**Comment by mehdok** [comment]
Closing the issue right now. Please feel free to open it anytime or create new one;
