### ISSUE TITLE
FCM is not working when background locator is running in background

### ISSUE THREAD

**Issue by tanvish99** [rekab-app/background_locator#165]
When background locator service is started my app stops receiving notifications and as soon as the background locator is stopped after some time the notifications are started to receive.

**Comment by tanvish99** [comment]
It throws this error
W/FirebaseInstanceId(12011): Service took too long to process intent: com.google.android.c2dm.intent.RECEIVE App may get closed.

**Comment by mehdok** [comment]
Hi @tanvish99 
Thank you for opening an issue and sorry that I missed your post.

Do you means `Push Notification` by firebase?
Can you share some code?

**Comment by tanvish99** [comment]
Yes push notification by firebase

**Comment by mehdok** [comment]
Can you share a working example?

**Comment by tanvish99** [comment]
in the updated version of flutter fcm it is working so I am closing this issue
