### ISSUE TITLE
Firestore stream is not listen with background locator

### ISSUE THREAD

**Issue by bhanuka96** [rekab-app/background_locator#167]
Firestore stream has not listened with this plugin.

Full Code

```
import UIKit
import Flutter
import GoogleMaps
import background_locator
import cloud_firestore

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    let filename = Bundle.main.infoDictionary?["GOOGLE_MAPS_API_KEY"] as! String
    GMSServices.provideAPIKey(filename)
    GeneratedPluginRegistrant.register(with: self)
    BackgroundLocatorPlugin.setPluginRegistrantCallback(registerPlugins)
     registerOtherPlugins()
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

    func registerOtherPlugins() {
        if !hasPlugin("io.flutter.plugins.firebase.cloudfirestore") {
            FLTFirebaseFirestorePlugin
                .register(with: registrar(forPlugin: "io.flutter.plugins.firebase.cloudfirestore") as! FlutterPluginRegistrar)
        }
    }
}

func registerPlugins(registry: FlutterPluginRegistry) -> () {
    if (!registry.hasPlugin("BackgroundLocatorPlugin")) {
        GeneratedPluginRegistrant.register(with: registry)
    }
}

```

Splash Screen

```
  @override
  void initState() {
    super.initState();
    _bls.registerPort();
    _bls.initPlatformState().then((value) {});
```

Home Page

```
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
      _bls.startLocationService(); // starting
      locationSubscription = _bls.port.listen(backgroundLocPort); // listen is working
    sixSubscription = _connectivityService.connectionStream.listen(connectionStream); // listen is working
      oneSubscription = db.getUser(driverUid).listen(getUser); //listen not working (any firestore stream not listen)

```
Background Locator Service

```
class BackgroundLocationService {
  static const String _isolateName = "LocatorIsolate";
  ReceivePort port = ReceivePort();

  Future<void> initPlatformState() async {
    await BackgroundLocator.initialize();
  }

  void registerPort() async {
    PermissionStatus permission = await LocationPermissions().requestPermissions(permissionLevel: LocationPermissionLevel.locationAlways);
    if (permission == PermissionStatus.granted) {
      IsolateNameServer.registerPortWithName(port.sendPort, LocationServiceRepository.isolateName);
    } else {
      repeat();
    }
  }

  void repeat() {
    registerPort();
  }

  static void callback(LocationDto locationDto) async {
    final SendPort send = IsolateNameServer.lookupPortByName(_isolateName);
    send?.send(locationDto);
  }

  void startLocationService() {
    Map<String, dynamic> data = {'countInit': 1};
    BackgroundLocator.registerLocationUpdate(LocationCallbackHandler.callback,
        initCallback: LocationCallbackHandler.initCallback,
        initDataCallback: data,
        disposeCallback: LocationCallbackHandler.disposeCallback,
        autoStop: false,
        iosSettings: IOSSettings(accuracy: LocationAccuracy.NAVIGATION, distanceFilter: 0),
        androidSettings: AndroidSettings(
            accuracy: LocationAccuracy.NAVIGATION,
            interval: 1,
            distanceFilter: 0,
            androidNotificationSettings: AndroidNotificationSettings(
                notificationChannelName: 'Location tracking',
                notificationTitle: 'OrelGo Driver Location Tracking',
                notificationMsg: 'Track location in background',
                notificationBigMsg:
                    'Background location is on to keep the app up-tp-date with your location. This is required for main features to work properly when the app is not running.',
                notificationIcon: '',
                notificationIconColor: Palette.defaultColor,
                notificationTapCallback: LocationCallbackHandler.notificationCallback)));
  }

  void stopLocationService() {
    BackgroundLocator.unRegisterLocationUpdate();
  }
}
```

**Comment by mehdok** [comment]
Why did you opened a new issue? :) 

Please create a small repository with your code, so I can run it;

**Comment by bhanuka96** [comment]
you said open an another issue, that's why I opened it https://github.com/rekab-app/background_locator/issues/158#issuecomment-734687746

**Comment by bhanuka96** [comment]
please check this https://github.com/bhanuka96/background-location-flutter.git

**Comment by mehdok** [comment]
> you said open an another issue, that's why I opened it [#158 (comment)](https://github.com/rekab-app/background_locator/issues/158#issuecomment-734687746)

I wasn't with you, I mentioned someone else :)) 

Thank you for the code, I'll check it out.

**Comment by mehdok** [comment]
@bhanuka96  I have spend some time on your project and I couldn't figure out what is the problem. I even added `-FIRDebugEnabled` to iOS project to see firebase debug log and everything was normal, but for some unknown reason the listener is not getting triggered. The only temporary solution is to delay initializing the plugin: 

````dart
Future.delayed(Duration(seconds: 1), () async {
      await BackgroundLocator.initialize();
    });
````

If you find the real problem I would be more than happy to hear it;

**Comment by bhanuka96** [comment]
@mehdok I am also tried this. But after init (`await BackgroundLocator.initialize();`), firebase listen not working.

I think this issue related to this https://github.com/FirebaseExtended/flutterfire/issues/4108#issuecomment-734723727

**Comment by mehdok** [comment]
It seems relevant, I'll keep eye on it and share with you if I found any solution;

ps: We have a `PR` that port this plugin for the Flutter plugin system, It would be nice if you could just test it to see if it fixes your problem or not. It's a wild guess but it worth a shot; #137

**Comment by hordeariibarley** [comment]
I'm having the same behavior at my app.
I tried to use StreamBuilder and StreamProvider, but without success on both. (I am emulating on IPhone, I still couldn't try on android).

@bhanuka96 Did you solve it already?

**Comment by sspatari** [comment]
> [FirebaseExtended/flutterfire#4108 (comment)](https://github.com/FirebaseExtended/flutterfire/issues/4108#issuecomment-734723727)
> 
> This solved my issue!

This really solve the firebase problem, any idea when will this be pushed to the official repos?

**Comment by mehdok** [comment]
I believe it's our problem, it would be nice if you ask it in the specified link;

**Comment by mehdok** [comment]
@Wian-TMC 
Thank you man, I really appreciate your help.
I'll take a look into that library to see what they have done.

**Comment by mehdok** [comment]
@Wian-TMC 
I tried to extract something from that plugin to help to solve our issue, the only thing that I could find is this issue [Audio Service interrupting firestore stream when starting](https://github.com/ryanheise/audio_service/issues/477)
The author explains that this is a firebase problem because of using a singleton, and he is trying to implement `audio_service plugin without using  `Isolate`.
