### ISSUE TITLE
Example Code is not working properly in IOS simulator

### ISSUE THREAD

**Issue by Shub-29** [rekab-app/background_locator#168]
The plugin is working good in android devices but when I tried to run in ios simulator, I am just getting the location only for one time. After that it is not working.

**Comment by mehdok** [comment]
Hi @Shub-29 

Thank you for opening an issue;

- Did you gave `always` permission?
- Are you running on simulator?
- Does the example works fine for you?
-It would be nice if you could create a working example of your app for me to check;

**Comment by Shub-29** [comment]
Yes I gave "always" permission and I am running it on simulator.

**Comment by mehdok** [comment]
Ok, simulator give you just one location, if you want to get new location change the location of simulator; referent to this [answer](https://stackoverflow.com/a/61207399/884076) if you have any problem doing it;

**Comment by Shub-29** [comment]
For me, the example works fine in android real devices. But in ios simulators it is not.

**Comment by Shub-29** [comment]
The problem is, it is giving location just for once. After that it is not capturing the location. If it would have given the same location every time , I had no problem.

**Comment by mehdok** [comment]
iOS does not work that way, please referent to my previous answer. iOS give you new location whenever new location is available, it doesn't return same location as android.

**Comment by Shub-29** [comment]
Got it. I hope it will work in background also. I will check it and close the issue. Thanks.
