### ISSUE TITLE
getting location updates even when the app is killed not working

### ISSUE THREAD

**Issue by Tapuyo** [rekab-app/background_locator#172]
Great job, but i need an update of location even app was killed by user. After killing the app notification was gone too, by the way i use real device on debuging and when i use emulator it is working properly.

**Comment by mehdok** [comment]
Hi @Tapuyo 
Thank you for opening an issue.

Usually, the problem with a real device is related to the battery monitor.
Please exclude the app and its service from any battery monitor or power-saving app.

Let me if it's working or not :)

**Comment by mehdok** [comment]
Closing the issue due to lack of information. Feel free to open it anytime;
