### ISSUE TITLE
Can we get location in ios following a particular time interval?

### ISSUE THREAD

**Issue by Shub-29** [rekab-app/background_locator#173]
So I am trying to use this plugin for capturing location points in our survey app every 10 secs. Is it possible to implement using this plugin? What I have heard that in ios it will give the location every time when it is changed. Can we control this behavior?

**Comment by mehdok** [comment]
Hi @Shub-29 
Thank you for opening an issue

As far as I know, iOS doesn't work with intervals, and it only gives you a new location when it is available.
But I would be more than happy to hear your solution if you found any;
