### ISSUE TITLE
Recording stops after 5 minutes from android oreo

### ISSUE THREAD

**Issue by K-Rafiki** [rekab-app/background_locator#177]
So, I tried a bunch of devices and it seems that the location service stops recording after 5 minutes whether in foreground or background. However, this only happens in devices over Android Nougat (7). It worked fine on my Nougat and Marshmallow devices, but stopped recording after 5 minutes in devices Oreo and Pie. I haven't tested on android 10 yet tho. Would love if you could fix this issue. I gave every permission to the app in all the cases, and made sure to set it on not optimized for battery.

**Comment by ferdinandfrank** [comment]
@K-Rafiki This should be the same issue as in https://github.com/rekab-app/background_locator/issues/169.

**Comment by mehdok** [comment]
Hi @K-Rafiki 
Thank you for opening an issue.
as @ferdinandfrank said, it's a known bug and you can see the solving progress in #169.
