### ISSUE TITLE
Example with notification Icon

### ISSUE THREAD

**Issue by marcusmvfa** [rekab-app/background_locator#187]
Please could you share with us an example using notification icon?
I've tried passing complete path to android mipmap, but i had no luck implementing it.

**Comment by mehdok** [comment]
This might help

https://github.com/rekab-app/background_locator/issues/48#issuecomment-773559387

**Comment by marcusmvfa** [comment]
I'll try it, thank you.

**Comment by marcusmvfa** [comment]
> This might help
> 
> [#48 (comment)](https://github.com/rekab-app/background_locator/issues/48#issuecomment-773559387)

Solved, thanks!!
