### ISSUE TITLE
[Question] - Documentation Request

### ISSUE THREAD

**Issue by angel1st** [rekab-app/background_locator#19]
Hi there,
I have just came across this plugin and it seems quite promising in its specific niche. I cannot however find any documentation - for instance I would like to know all `LocationSettings` parameters meaning for start.

**Comment by mehdok** [comment]
You are right, I will update the documentation this weekend.

**Comment by angel1st** [comment]
hey @mehdok - thanks for the docs update. One question though, re `wakeLockTime` - I am not sure, I understand what "Time for living service in background in meter" is about?

**Comment by mehdok** [comment]
Sorry for that, its `Time for living service in background in mimute`. I'll update the doc. Thanks for telling.

**Comment by hectorAguero** [comment]
> Perdón por eso, es `Time for living service in background in minute`. Actualizaré el documento. Gracias por contarme

@mehdok  So in the default value, the service will stop in 60 minutes? It's possible to set this without a limit, and only stop it when the user press a button on the app.

**Comment by mehdok** [comment]
@hectorAguero Yes it will keep the phone awake for 60 minutes and prevent it to sleep. 60 minutes is really long time for keeping phone awake and doing a energy consuming job like getting location via GPS, and I think it's more than enough to do your job, But if you need more time just set a hight number for this, eg. 1000.
It is just a safety guard to prevent draining phone battery.
