### ISSUE TITLE
Firebase.initializeApp does not work in callback

### ISSUE THREAD

**Issue by daichi000** [rekab-app/background_locator#196]
Hi, I tried this code, but the App crashes
```
Future<void> callback(LocationDto locationDto) async {
  await Firebase.initializeApp();
  Firestore.instance.collection("test").document().setData({
     "test": "data",
  });
  final SendPort send = IsolateNameServer.lookupPortByName(isolateName);
  send?.send(locationDto);
}
```

If except for `await Firebase.initializeApp();`, App doesn’t crash, but firestore doesn't work.
Can you please let me know the possible reason?

**Comment by hiteshkumartank** [comment]
Do changes on Application.kt file. 

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.pathprovider.PathProviderPlugin
import io.flutter.view.FlutterMain
import rekab.app.background_locator.IsolateHolderService
import io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin;
import io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin;


class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        IsolateHolderService.setPluginRegistrant(this)
        FlutterMain.startInitialization(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin("io.flutter.plugins.pathprovider")) {
            PathProviderPlugin.registerWith(registry.registrarFor("io.flutter.plugins.pathprovider"))
        }
        FlutterFirebaseCorePlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebase.core.FlutterFirebaseCorePlugin"));
        FlutterFirebaseFirestorePlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin"));

    }
}

**Comment by irwing844** [comment]
You must register the plugin. https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback

**Comment by joandervieira** [comment]
I have the same problem. 
What is the name package of the firebase ?
`FLTFirebaseCorePlugin.register(with: registrar(forPlugin: "io.flutter.plugins.firebase.core")!)`
Is it ?
