### ISSUE TITLE
Any progress on this plugin ?

### ISSUE THREAD

**Issue by fvisticot** [rekab-app/background_locator#2]
Did you plan to release this plugin with a production ready status ?
It would be very useful

**Comment by mehdok** [comment]
Sure there is a plan, but I need more people to test and find bugs so I can reach a more stable release.

**Comment by gpibarra** [comment]
I'm here

**Comment by gpibarra** [comment]
have anyone tried it on ios?

**Comment by mehdok** [comment]
@fvisticot stable version will be released in near future.

**Comment by mehdok** [comment]
@gpibarra Are you experiencing some sort of problems in iOS?

**Comment by mehdok** [comment]
@fvisticot First stable version released.
