### ISSUE TITLE
Write logs even when app is not running in the foreground.

### ISSUE THREAD

**Issue by viveknimkarde** [rekab-app/background_locator#20]
https://github.com/rekab-app/background_locator/blob/28f02ce0965302e95b9f55287fcd5abe04a16697/example/lib/main.dart#L36

Isolate port stops listening as soon as the app process is destroyed. 
So logs are not written when the app is not running. while the background locator is working fine. Should we write logs in the callback or keep it in on port listen function

**Comment by RomanJos** [comment]
I have the same question, I came accross [this medium article ](https://medium.com/stuart-engineering/keep-flutter-running-background-on-android-6ffc85be0234) where when flutter is killed the sticky service listen to this and start `FlutterNativeView` wich is different than `FlutterActivity` to execute a dart function, so there is no UI drawing whatsoever in the background. You need to wait `WidgetsFlutterBinding.ensureInitialized();` in your function before executing anything in background ([in their example it write in a file every seconds](https://github.com/ppicas/flutter-android-background/blob/master/lib/background_main.dart))
and this library pretty much do the same [see here](https://github.com/rekab-app/background_locator/blob/master/lib/callback_dispatcher.dart), even better, it only start the sticky service when you need it so you don't have a notification all the time

**Comment by mehdok** [comment]
I think one of the pull request caused this.

Remove this lines from example code and let me know if it fixed the problem:

```
@override
  void dispose() {
    IsolateNameServer.removePortNameMapping('LocatorIsolate');
    super.dispose();
  }
```

**Comment by viveknimkarde** [comment]
I tried the above change. Still no working.

**Comment by RomanJos** [comment]
After playing with I just wanted to point some problem that I'm facing right now :
if we kill FlutterActivity (in recent app) the ReceivePort is also killed so I did
```dart
if (IsolateNameServer.lookupPortByName('LocatorIsolate') != null) {
        BackgroundLocator.unRegisterLocationUpdate();
        IsolateNameServer.removePortNameMapping('LocatorIsolate');
      }
```
to re-create an isolate that is sending on the port I'm listening, I don't think its a good solution since I played with ctrl + space on vs code to see what I could do with IsolateNameServer. Maybe there is something to plug the isolate on another port I don't know instead of killing it like I did.

I can't use path_provider in the callback function (I believe there isn't something like `GeneratedPluginRegistrant.registerWith(flutterEngine);` in your service It would be cool to do something about it, in my case I want to write the LatLng list in a file and then when the app re-launch it fetch this file and show it on the polyline

**Comment by mehdok** [comment]
I'm not sure what is wrong with your code, But I removed those lines and the example  code worked for me just fine, I still can see the logs, @viveknimkarde I moved the app to background and also removed it from recent list and the logs kept coming as usual.

@RomanJos The callback and isolate is headless and is not part of any activity, so it can continue to live without attaching to anything.
So you don't need to recreate the Isolate, It will continue to live as long as you explicitly stop it.
Beside that `GeneratedPluginRegistrant.registerWith(flutterEngine);` is  an old method for creating plugins, with version 2 you don't need any of that.

**Comment by RomanJos** [comment]
> The callback and isolate is headless and is not part of any activity, so it can continue to live without attaching to anything.

My problem is that I can't use path_provider inside the callback function, I get a NotImplemented error (This is why I pointed `GeneratedPluginRegistrant`). So I'm unable to save the position in a file to retrieve it in the app. I've found [this example](https://github.com/ppicas/flutter-android-background) and it look quite like this library and what I want to achieve except they are able to store the data

> So you don't need to recreate the Isolate, It will continue to live as long as you explicitly stop it.

Yes but if I close the app in the recent app and then re open I will loose the port that the isolate communicate and couldn't listen and do my stuff etc. If you have a way to "retrieve" the port or create a new one and passing it to the isolate it would be perfect

And yeah I believe that this function import the native part of library so path_provider could work for example but I didn't look this much into it

**Comment by mehdok** [comment]
For the first part of your problem, right now I'm using path_provider to log into a file, look at the `file_manager.dart` inside the example, and it works even when you terminate the application, I will try to update the example to make this shine a bit more :).

For the second part of the problem, I will try to handle the situation you mentioned.

**Comment by RomanJos** [comment]
Yes but its not in the callback function, if you kill the app, the callback will be called and will try to send to the port without anyone listening to it and thus no log, I mean I didn't tried your example but I couldn't get any printed value from my side in the port.listen where I have one inside callback

**Comment by mehdok** [comment]
Just try the example and omit the lines i have mentioned and let me know if it is working for you or not.
Or you can share your code with me so i can have better picture of the problem.

**Comment by viveknimkarde** [comment]
@mehdok i used example code without dispose. Logs work fine when app is in the background. But not when it is killed as mentioned by @RomanJos. Seems like callback function is sending the messages and no listeners alive to save the logs.



Is there anyway I can use external packages like firestore or path_provider inside callback function without getting method NotImplemented error ?

**Comment by mehdok** [comment]
My assumption about logging in background was wrong and both of you were right. Although The `callback(LocationDto locationDto)` is getting called even if app getting terminated (removed from recent), BUT the `ReceivePort` stop listening as soon as app get terminated.
