### ISSUE TITLE
Background locator still update when device is not in motion

### ISSUE THREAD

**Issue by KelvinForteta** [rekab-app/background_locator#204]
The plugin still posts location information even when the device is not in motion, the device is plugged into my computer, but I still receive the speed that is greater than 0, even the longitude and latitude changes on every update.

What should I do to make it stop updating when not in motion?

**Comment by mehdok** [comment]
Hi @KelvinForteta 
Thank you for opening an issue.

Use [distanceFilter](https://github.com/rekab-app/background_locator/blob/c737ab47cb038f0a79d19cd5865b8042965b0436/lib/settings/locator_settings.dart#L15), and set it to a number like 20 meters, so you won't get any update while the device is still;

**Comment by KelvinForteta** [comment]
Ok thanks, I will give it a try.
