### ISSUE TITLE
is Google Play Service is must or not need?

### ISSUE THREAD

**Issue by function2000** [rekab-app/background_locator#205]
For this plugin, is Google Play Service is must or not need?  As in China, Google Play Service is not an option. 
Thanks for answer.

**Comment by mehdok** [comment]
Hi @function2000 
Thank you for opening an issue.

I have a setting in the [AndroidSettings](https://github.com/rekab-app/background_locator/blob/c737ab47cb038f0a79d19cd5865b8042965b0436/lib/settings/android_settings.dart#L44) to choose either Google or Android as your location service, please give it a try and let me know if you had have problem;

**Comment by function2000** [comment]
> Hi @function2000
> Thank you for opening an issue.
> 
> I have a setting in the [AndroidSettings](https://github.com/rekab-app/background_locator/blob/c737ab47cb038f0a79d19cd5865b8042965b0436/lib/settings/android_settings.dart#L44) to choose either Google or Android as your location service, please give it a try and let me know if you had have problem;

I changed the code like below:
        androidSettings: AndroidSettings(
            accuracy: LocationAccuracy.NAVIGATION,
            interval: 5,
            distanceFilter: 0,
            client: LocationClient.android,
But still not work, see the pic.  Can you try on your side?
![20210228165039](https://user-images.githubusercontent.com/4005363/109412828-24fd8c00-79e5-11eb-9b7d-225190d38d32.jpg)

**Comment by function2000** [comment]
it works when I go outside.  Thank you very much!
