### ISSUE TITLE
Callback is not triggered in iOS.

### ISSUE THREAD

**Issue by ZigaZumer** [rekab-app/background_locator#21]
I implemented the plugin and used the example. All the settings for Android and for iOS were implemented as written in the docs. In Android it works great but in iOS the callback function is never triggered. Any idea?

**Comment by mehdok** [comment]
Are you testing on real device or on simulator?
Receiving location on iOS depends on many things. Actually there is no interval for getting location like in android, in iOS the os decide when to send new location.

**Comment by ZigaZumer** [comment]
Tested on both simulator and real device. Not once the callback was triggered.

**Comment by umbertogrimaldi** [comment]
I'm experiencing the same issue....Any idea on how to solve this?

**Comment by juanlabrador** [comment]
Hi, I have the last version, in Android works but in iOS don't work the callback, I read the wiki many times, I don't know why the error.
