### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by Gnuhry** [rekab-app/background_locator#217]
is there already a plan to migrate the project to null safety?

**Comment by Gnuhry** [comment]
i just saw that there is a commit on master with null safety but when are you going to release it?

**Comment by mehdok** [comment]
Sorry for the delay, tomorrow I will do it;

**Comment by DebkanchanSamadder** [comment]
@mehdok I just noticed that I mistakenly updated the version from `1.4.1+1` to `1.5.1+1` instead of `1.5.0`. Please fix it before release

**Comment by mehdok** [comment]
@DebkanchanSamadder  Actually you did right. `+1` means first build and it is necessary for versioning;

**Comment by DebkanchanSamadder** [comment]
Mom are you proud now?

**Comment by mehdok** [comment]
@Gnuhry Package updated;

**Comment by Gnuhry** [comment]
yeah thanks.
