### ISSUE TITLE
Callback not Calling

### ISSUE THREAD

**Issue by marcusmvfa** [rekab-app/background_locator#225]
When called StartLocator the callback method aren't been called... The service logs "```
Locator service is already running
D/plugin  ( 3487): sendLocationEvent {callback=7376271144, location={altitude=0.0, heading=0.0, latitude=-26.9883467, accuracy=3.075, speed_accuracy=0.0, time=1.617131050765E12, is_mocked=false, speed=0.0, `longitude=-48.6360767}}
```"`

It only happens sometimes...

I need it working because the positions is sent to my server.

**Comment by surveshoeb** [comment]
Hi @marcusmvfa can you show me how did you fix this issue?

**Comment by marcusmvfa** [comment]
Hello @surveshoeb, I'm sorry but i didn't remember it was fixed since has passed almost an year
