### ISSUE TITLE
Only few callback when app is in background for Android Q version

### ISSUE THREAD

**Issue by vitoMacnil** [rekab-app/background_locator#24]
Good evening, 
I'm testing my app on an Android Q devices, and when the app goes to background, send only few datas. You have any suggest??? Thanks for the attention

**Comment by mehdok** [comment]
Can you see the notification?
Can you check if the service is running in background or it is stopped?

**Comment by vitoMacnil** [comment]
Yes, I see the notification and the debug console shows me the few operations done in background, but after this operations nothing was print in the console and nothing was sent ti my server side

**Comment by mehdok** [comment]
Are you testing example code? if not it would be nice if you share some code.

**Comment by vitoMacnil** [comment]
`import 'package:background_locator/background_locator.dart';
import 'package:background_locator/location_dto.dart';
import 'package:background_locator/location_settings.dart'
    as BackgroundLocationSettings;
import 'package:device_info/device_info.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:location/location.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Tracking Prototype',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Tracking Prototype Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _trackingEnabled = false;

  Timer timer;
  bool _serviceEnabled;
  PermissionStatus _permissionGranted;
  Location location;
  LocationData currentLocation;

  static final DeviceInfoPlugin deviceInfoPlugin = DeviceInfoPlugin();
  String deviceId;

  ReceivePort port = ReceivePort();
  static final _isolateName = 'LocatorIsolate';

  bool _first = true, _last = false;
  @override
  void initState() {
    super.initState();

    if (IsolateNameServer.lookupPortByName(_isolateName) != null) {
      IsolateNameServer.removePortNameMapping(_isolateName);
    }

    IsolateNameServer.registerPortWithName(port.sendPort, _isolateName);

    port.listen(
      (dynamic data) async {
        await _sendMobileData(deviceId, data, null);
      },
    );
    location = Location();
    initializeLocation();
    initPlatformState();
  }

  @override
  void dispose() {
    IsolateNameServer.removePortNameMapping(_isolateName);
    BackgroundLocator.unRegisterLocationUpdate();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('This device has id: $deviceId'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: _trackingEnabled ? Colors.green : Colors.red,
        onPressed: _enableDisableTracking,
        tooltip: _trackingEnabled ? 'Disable Tracking' : 'Enable Tracking',
        child: Icon(
          Icons.power_settings_new,
          color: Colors.white,
        ),
      ),
    );
  }

  Future<void> initializeLocation() async {
    //check location permission and service enabled
  }

  Future<void> initPlatformState() async {
    await BackgroundLocator.initialize();
    await BackgroundLocator.isRegisterLocationUpdate().then(
        (bool isRunning) => debugPrint('Running ${isRunning.toString()}'));
  }

  void _enableDisableTracking() {
    setState(() {
      _trackingEnabled = !_trackingEnabled;
    });

    if (_trackingEnabled) {
      BackgroundLocator.registerLocationUpdate(
        callback,
        androidNotificationCallback: notificationCallback,
        settings: BackgroundLocationSettings.LocationSettings(
          notificationTitle: "RemoteAngel Human",
          notificationMsg: "We follow you!!!",
          accuracy: BackgroundLocationSettings.LocationAccuracy.HIGH,
          distanceFilter: 0,
          interval: 1,
          wakeLockTime: 20,
          autoStop: false,
        ),
      );
    } else {
      BackgroundLocator.unRegisterLocationUpdate();
      debugPrint('Unregistered location update!!!');
      _last = true;
      Future.delayed(Duration(seconds: 1)).whenComplete(() => location
          .getLocation()
          .then((LocationData lastLocation) =>
              _sendMobileData(deviceId, null, lastLocation)));
    }
  }

  Future<void> _sendMobileData(String deviceId, LocationDto currentLocationDto,
      LocationData currentLocationData) async {
        //there is the API call to send locations to server side
        debugPrint(
            'Sent => $result at ${DateTime.now().toString()} with event => ${mobileDataToSend.event}');
  }

  static void callback(LocationDto locationDto) async {
    final SendPort send = IsolateNameServer.lookupPortByName(_isolateName);
    send?.send(locationDto);
  }

  static void notificationCallback() {
    debugPrint('notificationCallback');
  }
}
`
This is my code. Thanks for attention

**Comment by vitoMacnil** [comment]
Ok i found the issue.
I'm using another library to get service status, and the two libraries conflicts. 
Sorry for waste your time. This flutter package is very good
