### ISSUE TITLE
App crash : when i try to stop service after i kill app 

### ISSUE THREAD

**Issue by alfaruqrizqi18** [rekab-app/background_locator#245]
hi, when i start and kill my app i launch my app again and try to stop service, it crash
I use this version 1.4.0+1

**Comment by alfaruqrizqi18** [comment]
I got this error 
![image](https://user-images.githubusercontent.com/43517239/120764474-60f34080-c542-11eb-8bef-c839e70598af.png)

**Comment by ferdinandfrank** [comment]
@alfaruqrizqi18 I had the same issue and it seems to be fixed in the latest release `1.6.1+1-beta`.

**Comment by alfaruqrizqi18** [comment]
@ferdinandfrank thank you

**Comment by rahuldange09** [comment]
@alfaruqrizqi18  Please close the issue if it is fixed for you
