### ISSUE TITLE
App hangs after awaiting BackgroundLocator.unRegisterLocationUpdate() when background locator is not running

### ISSUE THREAD

**Issue by Wian-TMC** [rekab-app/background_locator#262]
Call `BackgroundLocator.unRegisterLocationUpdate()` when the background locator is not running. The reason for this was to combat the issue regarding the unreliable return of `BackgroundLocator.isRunning()` on iOS. Because of this I always call `BackgroundLocator.unRegisterLocationUpdate()` to ensure the locator is killed, even if it was not running, but calling `BackgroundLocator.unRegisterLocationUpdate()` when the service is not running blocks the application because it never returns when awaited for.

When the background service is not running, the response of `BackgroundLocator.unRegisterLocationUpdate()` outputs `Locator service is not running, nothing to stop` in the terminal, but fails to return when awaited, and therefore the app just hangs forever waiting for `BackgroundLocator.unRegisterLocationUpdate()` to resolve.

Simple solution would be to just return the future when this happens.

**Comment by mehdok** [comment]
Hi @Wian-TMC 
Thank you for opening an issue;

Fixed in [c2b66f9](https://github.com/rekab-app/background_locator/commit/c2b66f98a66b5fa7d7029d1dac1bec3d9fef35f1);
