### ISSUE TITLE
InitCallback not working at first call

### ISSUE THREAD

**Issue by LeoHub-dev** [rekab-app/background_locator#272]
Hello everybody, when i call the "BackgroundLocator.registerLocationUpdate" function, the first time. The initCallback is not being called. But the normal callback does work. On the second call of the function, everything runs perfect. Any idea why this happens? Im at version 1.4.0+1

![image](https://user-images.githubusercontent.com/7474084/133014925-e7f71dcd-1f4a-49cf-8d25-11b00f4dab44.png)

**Comment by mehdok** [comment]
Hi @LeoHub-dev 
Thank you for opening an issue;

Please use the latest version [![pub package](https://img.shields.io/pub/v/background_locator.svg)](https://pub.dartlang.org/packages/background_locator) and see if this behavior still persists;

**Comment by LeoHub-dev** [comment]
Hello @mehdok, ok i will test in a new project just to check. Sadly in the actual project right now is not exactly posible to migrate to null safety, since is a large project.

**Comment by mehdok** [comment]
Greate, thanks;

**Comment by MoacirSchmidt** [comment]
I can confirm this issue also occurs in v1.6.6

**Comment by allanguintu** [comment]
Hello @mehdok, this issue is still present in v1.6.12.
Any idea how to work around this issue?

Thank you.

**Comment by MoacirSchmidt** [comment]
Congratulations for you great package! unfortunately this issue makes it completely unfeasible since there is no other way to pass data to background serve
