### ISSUE TITLE
Example app is not running ... 

### ISSUE THREAD

**Issue by Nasirdev74** [rekab-app/background_locator#282]
I'm trying to implement the example app of this repository. 
I added this dependency: 
  background_locator: ^1.6.6
  location_permissions: ^3.0.0+1

& copied all file from background_locator/example/lib/ 
I tried to run the main function. 
The app is running on the emulator. 
& I got this on my console: 

I/flutter ( 4218): Initializing...
I/flutter ( 4218): Initialization done
I/flutter ( 4218): Running false

It says the app is initialized. but the service is not running. Can anyone help me please.
I followed the setup steps from the guideline.
/rekab-app/background_locator/wiki/Setup

**Comment by ClaudeChey** [comment]
change the location_permission to [permission_handler](https://pub.dev/packages/permission_handler)

**Comment by bardram** [comment]
I also changed to using the `permission_handler` plugin (the `location_handler` plugin is discontinued). 

However, if you're on Android >=11, I had to set the location permissions manually - see this page:

* https://developer.android.com/training/location/permissions#request-background-location
