### ISSUE TITLE
How can I use plugin inside callback?

### ISSUE THREAD

**Issue by vimalmistry** [rekab-app/background_locator#34]
I want to call api on location change. I want to attach JWT_TOKEN which is stored in shared preferences. I am facing.

`E/flutter (10000): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

**Comment by RomanJos** [comment]
Can you show `LocationService.kt` ? Look like you didn't do the step 3 of Android. At the moment we can't use plugins on IOS by the way

**Comment by vimalmistry** [comment]
@RomanJos I followed all 3 steps.
 I created Application.kt and configured in manifest.xml.
I am not familiar  with native programming.
Why IOS is not working? there is steps for configure in IOS.

**Comment by mehdok** [comment]
@vimalmistry The Document and the code need to be updated, I will do it this weekend. Please be hold until then.

**Comment by vimalmistry** [comment]
@mehdok ohh :( Did you updated doc? I found some new informations in readme.md
One question. What is requirement of minimum android version? My client complaints it is not working on their older devices!

**Comment by mehdok** [comment]
Minimum android sdk is 16.

**Comment by RomanJos** [comment]
Actually I modified the README 3 days ago so make sure to match changes on your project, it may resolve your issues 😉 
I'm using it on a real Android 4.4.2 (API 19) and it work well I only have issue setting the accuracy to HIGH so I left it to NAVIGATION

**Comment by mehdok** [comment]
@RomanJos Sorry your changes in document isn't merged yet. If there is something that can help @vimalmistry please copy paste it here.

**Comment by RomanJos** [comment]
No I mean the one that are already merged 
> I created Application.kt and configured in manifest.xml.

Its LocationService.kt on the readme

**Comment by vimalmistry** [comment]
Thanks for replies. I actually configured using old doc (Application.kt). It works very  well in most devices  Except some devices and also I can not run it on emulator. But in physical device it works. But I found service is terminated after reboot. Is there any quick fix to auto start on reboot.
I am not a native developer. So I don't know much about .kt and .java file. I am just copy pasting every time.😇

**Comment by RomanJos** [comment]
Thats strange it work on some devices but not even on the emulator, have you tried to run the example ? Starting at boot mean that we need a way to start the plugin directly from kotlin and not dart and I think it would require a lot of changes idk

And i do the same lol

**Comment by mehdok** [comment]
@vimalmistry I'm not sure why you can not get it working on some device or simulator, But I can confirm that the plugin is working fine on simulator, both Android and iOS.

On Android I can add the `RECEIVE_BOOT_COMPLETED`, it's not that hard to restart service when device rebooting, But it is something that only Android supports, as I know there is no similar feature on iOS, so for keeping everything equal I won't do it.

**Comment by TahaMalas** [comment]
> Thanks for replies. I actually configured using old doc (Application.kt). It works very well in most devices Except some devices and also I can not run it on emulator. But in physical device it works. But I found service is terminated after reboot. Is there any quick fix to auto start on reboot.
> I am not a native developer. So I don't know much about .kt and .java file. I am just copy pasting every time.😇

Hey, can you tell me how you managed to solve the issue? I'm getting the same problem with SharedPreferences package, while I'm trying to use it on the static callback function

**Comment by gpibarra** [comment]
Have you followed the steps in the documentation?

[https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback](url)

**Comment by khairu-aqsara** [comment]
i have same case and problem with you, but i follow step on https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback and it's work, here is my Application.kt

```
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin;
import io.flutter.view.FlutterMain
import rekab.app.background_locator.LocatorService

class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        LocatorService.setPluginRegistrant(this)
        FlutterMain.startInitialization(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin("io.flutter.plugins.sharedpreferences")) {
            SharedPreferencesPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.sharedpreferences"))
        }
    }
}
```
and change  the Manifestfile.

```
<application
        android:name=".Application"
```

you need add shared pref plugin,change 
```
import io.flutter.plugins.pathprovider.PathProviderPlugin
```
to this
```
import io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin;
```
and change 
```
if (!registry!!.hasPlugin("io.flutter.plugins.pathprovider")) {
    PathProviderPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.pathprovider"))
 }
```
to this
```
 if (!registry!!.hasPlugin("io.flutter.plugins.sharedpreferences")) {     
   SharedPreferencesPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.sharedpreferences"))
}
```

and in the static callback just use the shared pref plugin as usual
```
SharedPreferences prefs = await SharedPreferences.getInstance();
String somthing = prefs.getString('somthing');
```

**Comment by wemersonrv** [comment]
> @vimalmistry I'm not sure why you can not get it working on some device or simulator, But I can confirm that the plugin is working fine on simulator, both Android and iOS.
> 
> On Android I can add the `RECEIVE_BOOT_COMPLETED`, it's not that hard to restart service when device rebooting, But it is something that only Android supports, as I know there is no similar feature on iOS, so for keeping everything equal I won't do it.

@mehdok  Any chance to convince you to make this implementation for Android?

Almost 90% here in Brazil is android: https://gs.statcounter.com/os-market-share/mobile/brazil

And worldwide is not so different: https://gs.statcounter.com/os-market-share/mobile/worldwide

**Comment by mehdok** [comment]
@wemersonrv I think I can do that this weekend.

**Comment by MazEbeid** [comment]
Whats the Java equivalent to this 

`import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin;
import io.flutter.view.FlutterMain
import rekab.app.background_locator.LocatorService

class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        LocatorService.setPluginRegistrant(this)
        FlutterMain.startInitialization(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin("io.flutter.plugins.sharedpreferences")) {
            SharedPreferencesPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.sharedpreferences"))
        }
    }
}`

Can I add a Kotlin file to my flutter app when it was created using Java?

**Comment by ozz-rjq** [comment]
@MazEbeid thanks! can you help with ios configuration?

**Comment by MazEbeid** [comment]
I have no experience with iOS but this is very important to me at the
moment so I am spending time on it and I will look into how I can
contribute more.

I have tested last night the plugin while the app was in the background for
2hrs and I got a ping on iOS every 1 second or two.

I was out for 2 hrs and spent an hour whole the phone was locked and
stationary and still got some good pings.

I will be moving on to trying to get this to work while the app is
suspended. I think to start with I need to figure out if this is something
that can be done by firing a background service .. the problem with those
is that they cant be faster than 15minutes and also this is not guaranteed
and depends on how the OS prioritises your app.

**Comment by mehdok** [comment]
@MazEbeid @ozz-rjq There is a bug with iOS that prevent that app to get a gps fix while app is terminated in iOS (or at least get a fix every 500 meter or so). Also there is a PR [#59](https://github.com/rekab-app/background_locator/pull/59) which address this issue, but there is a bug with it too. It would be appreciated if anyone can help with that.
