### ISSUE TITLE
androidNotificationCallback is not optional!

### ISSUE THREAD

**Issue by TheMisir** [rekab-app/background_locator#35]
In documentation it says that `androidNotificationCallback` is optional parameter but the plugin crashes if `androidNotificationCallback=null`.

Also, please use correct [semver](https://semver.org/) versioning. You made a breaking change but increased minor version instead of major version. If minor version is changed the changes should be backward compatible.

**Comment by mehdok** [comment]
It's a known bug and it will be fixed.

**Comment by mehdok** [comment]
#36 Make android notification callback optional.
