### ISSUE TITLE
Issue  on release build 

### ISSUE THREAD

**Issue by hpsolver** [rekab-app/background_locator#352]
E/flutter ( 5395): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:location_sharing/location_callback_handler.dart' not found.

**Comment by bornakpaul** [comment]
use @pragma("vm:entry-point") before the class or function, so that the compiler knows that this particular class/function will be used from native code

**Comment by hpsolver** [comment]
@bornakpaul by adding "@pragma("vm:entry-point")" is fixed last crash. But now release build not updating latlng on firebase.

here is my code it's working fine only debug build :
 Future<void> callback(LocationDto locationDto) async {
    print('$_count location in dart: ${locationDto.toString()}');
    await Firebase.initializeApp();
    FirebaseReference.userSecret.doc(Globals.firebaseUser?.uid).update(
        {"latitude": locationDto.latitude, "longitude": locationDto.longitude});
    final SendPort? send = IsolateNameServer.lookupPortByName(isolateName);
    send?.send(locationDto);
    _count++;
  }

**Comment by bornakpaul** [comment]
@hpsolver i am on flutter 3.0.5 and it works fine for me.

**Comment by hpsolver** [comment]
@bornakpaul my flutter version is 3.3.3

**Comment by hpsolver** [comment]
@bornakpaul could you help me on this version ?

**Comment by bornakpaul** [comment]
@hpsolver i will have to look into this, might take some time. meanwhile, if you are in a hurry you can try to degrade the version and check

**Comment by hpsolver** [comment]
okay i will

**Comment by hpsolver** [comment]
@bornakpaul thanks on flutter 3.0.5 is working fine
