### ISSUE TITLE
Run flutter code from androidNotificationCallback

### ISSUE THREAD

**Issue by pkuzco** [rekab-app/background_locator#38]
Any suggestion for how to display an alert or rebuild part of the UI from androidNotificationCallback? 

I tried `SchedulerBinding.instance.addPostFrameCallback()` and `WidgetsBinding.instance.addPostFrameCallback()` with no success in getting that working.

**Comment by pkuzco** [comment]
I resolved the issue using communication between isolates.

**Comment by RomanJos** [comment]
I think you can do
```dart
final SendPort send = IsolateNameServer.lookupPortByName(_isolateName);
send?.send("Notification");
```
and do what you want in the listen callback, the only problem is if the app is killed, nothing will be listening so the best way for this is to put a global variable on `true` for example and then on app start check if its true but we're having some problem for this #31 

Oh you just did that lol
