### ISSUE TITLE
 MissingPluginException

### ISSUE THREAD

**Issue by Flavsditz** [rekab-app/background_locator#39]
I am posting this here since the error is connected to the usage with your package. I know the error shows another though:

### Background
I wanted to integrate this plugin to an existing, but a bit dated, project. So I followed everything on the installation and setup but encountered too many errors.
I decided to test the example on this github and everything worked well as expected.
I couldn't find the problem so I decided to start a fresh project.
I did and I copied the main and file_manager files from the example project.

### Error
The app was now starting and asking for the permission to use the location of the device.
But when it tried to get the location and save to the log file I got:
`(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)`

### What I have done

- After googling similar errors a lot of solutions point to simply `flutter clean` or `flutter pub cache repair` as well as restarting Android Studio or something.
-- I've tried all these solutions but could not make it work.
- I have re-installed flutter and android studio even
- I have checked the Android generated files as well as the Plugins folder and everything is generated correctly and the bindings are also done

### Data
I've prepared an example project here: [https://github.com/Flavsditz/test_plugin](https://github.com/Flavsditz/test_plugin)
- **Flutter Version**: 1.12.13+hotfix.9 • channel stable •
- **Dart Version**: 2.7.2
- **IntelliJ Version**: Ultimate 3.6.2
- **Flutter Doctor**:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.1)
[✓] Connected device (1 available)
```

I would love to make this plugin work since it seems to be exactly what I need. So any help would be much appreciated.

Thank you for developing this!

**Comment by Flavsditz** [comment]
I don't understand why this works in the example but not on a fresh project... The versions in the pubspec are the same

**Comment by hectorAguero** [comment]
You don't follow this step https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback

**Comment by Flavsditz** [comment]
You are completely right! 
I just feel silly... 
Originally I didn't want to use another plugin inside a callback but as the project didn't work I've copied the example and forgot to go through the rest of the configuration.
I was in so deep that I forgot to look at it.

Thanks!!!
