### ISSUE TITLE
Unregistering twice results in app crash

### ISSUE THREAD

**Issue by Sly2024** [rekab-app/background_locator#4]
In your app example, il you tap on stop without hitting start, the app crash.
The same crash happen if you try to unregister twice.
I would expect the app not to crash or it should be possible to test if the service is already registered

**Comment by mehdok** [comment]
[d5aa2a7ccf71765c1a7da2bf97f95a435231c3f2](url)

**Comment by Sly2024** [comment]
Works fine !
