### ISSUE TITLE
Notification icon

### ISSUE THREAD

**Issue by wemersonrv** [rekab-app/background_locator#40]
There is a way to use an icon for notification to replace the default square icon?

**Comment by gpibarra** [comment]
see 
[https://github.com/rekab-app/background_locator/blob/7f6e11d7bd40a1909d97c77df757da3a795451c4/lib/location_settings.dart#L22](https://github.com/rekab-app/background_locator/blob/7f6e11d7bd40a1909d97c77df757da3a795451c4/lib/location_settings.dart#L22)

**Comment by wemersonrv** [comment]
> see
> https://github.com/rekab-app/background_locator/blob/7f6e11d7bd40a1909d97c77df757da3a795451c4/lib/location_settings.dart#L22

Cool. Thanks

**Comment by wemersonrv** [comment]
> see
> https://github.com/rekab-app/background_locator/blob/7f6e11d7bd40a1909d97c77df757da3a795451c4/lib/location_settings.dart#L22

Looking here, i'm already using the application icon.

```xml
<application
        android:name="br.xocorona.LocationService"
        android:label="Xô Corona"
        android:icon="@mipmap/ic_launcher">
```

But just shows a white square icon... see:

![image](https://user-images.githubusercontent.com/2028673/79574581-c2cebd80-8096-11ea-9134-a64ee82e06da.png)


Do i need to use a specific icon settings to show here ?

**Comment by gpibarra** [comment]
That is not a problem of the library. It is a flutter or Android problem. Maybe your app icon is colored. In android the notification icons are one ink. Android transforms all colors to black and the background must be transparent (png).

**Comment by wemersonrv** [comment]
> That is not a problem of the library. It is a flutter or Android problem. Maybe your app icon is colored. In android the notification icons are one ink. Android transforms all colors to black and the background must be transparent (png).

Ok understand. It works now, Cool!
