### ISSUE TITLE
There is a way to config locator to starts when device is restarted ?

### ISSUE THREAD

**Issue by wemersonrv** [rekab-app/background_locator#41]
Hello.

There is a way to config locator to starts when device is restarted ?

My app is to count hours user is in a specific place, so; when mobile is restarted, need to continue capture locations, even if user forgot to open the app to start the captures.

**Comment by anirudhsharma392** [comment]
@wemersonrv  did you found any solution for this ??

**Comment by anirudhsharma392** [comment]
@wemersonrv  did you found any solution for this

**Comment by gpibarra** [comment]
This was written on another issue:

[https://github.com/rekab-app/background_locator/issues/34#issuecomment-612360164](https://github.com/rekab-app/background_locator/issues/34#issuecomment-612360164)

**Comment by wemersonrv** [comment]
> @wemersonrv did you found any solution for this ??

Hello. Nope. Unfortunately I couldn't.





> This was written on another issue:
> 
> [#34 (comment)](https://github.com/rekab-app/background_locator/issues/34#issuecomment-612360164)

As @mehdok says on the quoted comment below, it don't has a way to do that... Will need to count on user to reopen app/service to restart captures.

**Comment by mehdok** [comment]
[  Restart-service-on-device-reboot  ](https://github.com/rekab-app/background_locator/wiki/Restart-service-on-device-reboot)

**Comment by wemersonrv** [comment]
> [ Restart-service-on-device-reboot ](https://github.com/rekab-app/background_locator/wiki/Restart-service-on-device-reboot)

Not works here. Did i miss something?!


Below my **AndroidManifest.xml**

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="br.myapp">

    <!-- App permissions -->
    <uses-permission android:name="android.permission.INTERNET"/>

    <!-- Background Location permissions -->
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>


    <application
        android:name="br.myapp.LocationService"
        android:label="My App"
        android:icon="@mipmap/ic_launcher">

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
           android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <!-- Background Location configuration -->
        <receiver
            android:name="rekab.app.background_locator.LocatorBroadcastReceiver"
            android:enabled="true"
            android:exported="true"/>
        <service
            android:name="rekab.app.background_locator.LocatorService"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="true"/>
        <service
            android:name="rekab.app.background_locator.IsolateHolderService"
            android:permission="android.permission.FOREGROUND_SERVICE"
            android:exported="true"/>
		<receiver android:name="rekab.app.background_locator.BootBroadcastReceiver"
            android:enabled="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>

        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

```

**Comment by wemersonrv** [comment]
Sorry! My bad!

after about 40 seconds he started the background locator.

**Is alive! bwahahahahahahah!**

**Comment by pkuzco** [comment]
Is relaunching the service on device reboot supported on iOS?

I see that this plugin calls `startMonitoringSignificantLocationChanges` on iOS which based on Apple's documentation, the service should be relaunched after a significant location change of 500m or more.
Has anybody tested that this feature works on iOS? I tried both on the emulator and real device - doesn't work on either.

**Comment by wemersonrv** [comment]
> Is relaunching the service on device reboot supported on iOS?
> 
> I see that this plugin calls `startMonitoringSignificantLocationChanges` on iOS which based on Apple's documentation, the service should be relaunched after a significant location change of 500m or more.
> Has anybody tested that this feature works on iOS? I tried both on the emulator and real device - doesn't work on either.

This specific feature @mehdok make is for android only...
