### ISSUE TITLE
androidNotificationCallback gets called for unrelated notifications

### ISSUE THREAD

**Issue by pkuzco** [rekab-app/background_locator#42]
androidNotificationCallback gets called when clicking notifications that are shown by other flutter plugins. A payload/id (String) should be passed to androidNotificationCallback, so we are able to tell whether this was triggered as a result of clicking this plugin's foreground service notification or some other unrelated notification.

How to reproduce?
1.  Show some notification using flutter_local_notifications
2. Click on that shown notification from (1)
3. androidNotificationCallback will be called even though the notification was not shown by background_locator.

**Comment by mehdok** [comment]
That's really really strange, can you create a simple project to test this?

**Comment by pkuzco** [comment]
I think you need to specify a unique action name when you build an Intent for notification, and then check that you got that specific action before calling androidNotificationCallback; similar to what flutter_local_notifications is doing:

https://github.com/MaikuB/flutter_local_notifications/blob/60072d6806bf531ac2ec88570027a7a9445c7184/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L946

https://github.com/MaikuB/flutter_local_notifications/blob/60072d6806bf531ac2ec88570027a7a9445c7184/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L133
