### ISSUE TITLE
Change to MIT license

### ISSUE THREAD

**Issue by yoavrofe** [rekab-app/background_locator#46]
GPL is a very restrictive license, which makes the plugin unsuitable for most uses.
I suggest changing to MIT.

**Comment by mehdok** [comment]
What restriction and use case do you referring to?

**Comment by yoavrofe** [comment]
Using this plugin means that you must open source your app using the same license. That's why it not used anymore for plugins.

**Comment by mehdok** [comment]
I didn't think of this feature as a restriction, But you are right. let me investigate the condition of changing the license.

**Comment by scotty86** [comment]
Yeah, your plugin works very well so far! Thank you!
But GPL is a nono for me. MIT would be awesome.

**Comment by mehdok** [comment]
@RomanJos 
@marceloneppel 
@gpibarra 

You contributed to this library, So I need your agreement to change the license from `GPL3` to `MIT`.

Do you agree?

**Comment by RomanJos** [comment]
The two are okay for me

**Comment by marceloneppel** [comment]
> @RomanJos
> @marceloneppel
> @gpibarra
> 
> You contributed to this library, So I need your agreement to change the license from `GPL3` to `MIT`.
> 
> Do you agree?

I agree.

**Comment by gpibarra** [comment]
I agree!

**Comment by yoavrofe** [comment]
Great. Thanks! Please note that the original license file was not changed, just a new license.md file added. I suggest removing the older one.

**Comment by mehdok** [comment]
@yoavrofe Thanks for reminding;
