### ISSUE TITLE
Notification icon works only in debug, when make a release app, the icon not works.

### ISSUE THREAD

**Issue by wemersonrv** [rekab-app/background_locator#48]
Hi, make icon and name it `ic_background` and add it to each folder `midmap-hdpi`, hmdpi, xhdpi, etc... and works fine on debug. See:

**Icon on status bar (debug)**
![image](https://user-images.githubusercontent.com/2028673/80327499-ac510080-8812-11ea-9b0d-e0415a0357f3.png)

**Icon on notification dialog (debug)**
![image](https://user-images.githubusercontent.com/2028673/80327488-a2c79880-8812-11ea-8324-e124881f5070.png)

Testing in an emulator or installing the `app-debug.apk` on a device it works... but when install the `app-release.apk` or a published version from play store, notification icon not works. The icon is almost hidden on device bar, and in notification continues to show a single square. See: 

**Icon on status bar on my device (release)**
See, the icon is resumed to a single pixel.... almost invisible.
![image](https://user-images.githubusercontent.com/2028673/80329173-d3f69780-8817-11ea-8c8c-83620a18837c.png)

**Icon on notification dialog on my device (release)**
Just renders a square...
![image](https://user-images.githubusercontent.com/2028673/80329188-e7a1fe00-8817-11ea-8c51-5e5d1512c403.png)

Test with three different icons, and get the same issue. On each test, use the versions according to the sizes:

![image](https://user-images.githubusercontent.com/2028673/80329426-ad852c00-8818-11ea-93ec-4be1d9f9886f.png)

**Comment by gpibarra** [comment]
It seems more like an android problem than a library problem.
What versions do you have in the emulate? What do you have on the physical device?
Make sure the icon is png with a transparent background and a single color. Maybe there is a pixel with a different color that is what you see.

**Comment by wemersonrv** [comment]
> It seems more like an android problem than a library problem.
> What versions do you have in the emulate? What do you have on the physical device?
> Make sure the icon is png with a transparent background and a single color. Maybe there is a pixel with a different color that is what you see.

Emulator: Google Pixel 2 (Android 9)
Device: Moto G5 ( Android 7.1,1 )... but i have 500 testers working my app in beta and all of them have the same issue.

Here the icon.. It is a 1 color (black) png with transparent background... If different, will not work in emulator... i tested other icons and colors with no transparent background and nowt works in debug... in short... Icon is good and works in debug... **even when i install the `app-debug.apk` in my device**:

![image](https://user-images.githubusercontent.com/2028673/80382385-9c6c0780-8878-11ea-9c69-6369eaee42ba.png)

Used an 900x900 PNG icon with base to generate all `mipmap-xhdpi`  icons... 

See the `ic_icons` on my project:

![image](https://user-images.githubusercontent.com/2028673/80382841-2ae08900-8879-11ea-98a1-fc767e897a57.png)

**Comment by gpibarra** [comment]
try changing the dimensions of the icon

Small Notification Icon (mdpi) | 24x24
Small Notification Icon (hdpi) | 36x36
Small Notification Icon (xhdpi) | 48x48
Small Notification Icon (xxhdpi) | 72x72
Small Notification Icon (xxxhdpi) | 96x96

[https://documentation.onesignal.com/docs/customize-notification-icons](https://documentation.onesignal.com/docs/customize-notification-icons)

**Comment by wemersonrv** [comment]
> try changing the dimensions of the icon
> 
> Small Notification Icon (mdpi) | 24x24
> Small Notification Icon (hdpi) | 36x36
> Small Notification Icon (xhdpi) | 48x48
> Small Notification Icon (xxhdpi) | 72x72
> Small Notification Icon (xxxhdpi) | 96x96
> 
> https://documentation.onesignal.com/docs/customize-notification-icons

I'm using the right dimension for **?dpi**. This is not the problem. The problem is the icon is not rendered right when in **release**... Just in **debug*. If the icons were out of size, they would not have been rendered correctly even in the debug. The `home` icon i add in my previous post is only to show a sinle color and final file that was used to generate each dimension icon. 

See below, try with anoter icon, creating each mdpi/hdpi/xdpi/etc icon with right dimensions (24x24 36x36, etc)... works on debug, but not in release:

**debug**
![image](https://user-images.githubusercontent.com/2028673/80552001-ab97a600-899b-11ea-98b2-5f6f4755ed30.png)

**release**
See that in release, i made a zoom to show a single pixel rendered. 
![image](https://user-images.githubusercontent.com/2028673/80552105-fc0f0380-899b-11ea-9596-c6a12b919816.png)

**Comment by moovida** [comment]
I can confirm that the notification icon works flawless. It is most probably an issue of the image not being properly created.

Best you use this online tool: http://romannurik.github.io/AndroidAssetStudio/icons-notification.html

I made it like this and it works perfectly.

**Comment by wemersonrv** [comment]
> I can confirm that the notification icon works flawless. It is most probably an issue of the image not being properly created.
> 
> Best you use this online tool: http://romannurik.github.io/AndroidAssetStudio/icons-notification.html
> 
> I made it like this and it works perfectly.

Not works. I'm created the icons using this tool... test with my own image, and test with the same image in tool library (home icon on clipart)... none of them works.

When run in debug (emulator or device via adb) it works... **fine fine** but when make a release not works.

**Comment by wemersonrv** [comment]
Hello.

Working now. I just have to add a reference for the icon on **res/drawable/launch_background.xml**:

```xml]
<?xml version="1.0" encoding="utf-8"?>
<!-- Modify this file to customize your launch splash screen -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
	<item android:drawable="@android:color/white" />
	<!-- You can insert your own image assets here -->
	<item>
		<bitmap android:gravity="center" android:src="@mipmap/ic_background" />
	</item>
</layer-list>
```

**Comment by scotty86** [comment]
fml (I know, best start for a comment, but it took me hours to figure it out...)

**Problem:**
I always got a white square as notification icon. My launch icon is a grey square with some text.

**What I tried:**
- I generated the required image-files with https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_ac_unit
  - my icon-name is ic_background 
  - because I selected an icon the subdirs are res/drawable-*
- I copied the content of the downloaded zip-file to path_to_app_project/android/app/src/main
- I added following to the application-tag in android/app/src/main/AndroidManifest.xml
```xml
<meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_background" />
```
- I tried: (**But I think it's wrong.** This file is for splash screens as its comments say. Therefore I **removed it afterwards**.)
> Hello.
> 
> Working now. The icons are ok. But i have to add a reference for them on **res/drawable/launch_background.xml**:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> 
> <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
> 	<item android:drawable="@android:color/white" />
> 	
> 	<item>
> 		<bitmap android:gravity="center" android:src="@mipmap/ic_background" />
> 	</item>
> </layer-list>
> ```

Nothing worked, still got the dammit white square :rage:

**Solution:**
I defined the icon in the LocationSettings:
```javascript
BackgroundLocator.registerLocationUpdate(
	callback,
	//optional
	androidNotificationCallback: notificationCallback,
	settings: LocationSettings(
		accuracy: LocationAccuracy.NAVIGATION,
		notificationTitle: "Awesome title",
		notificationMsg: "Event more awesome text",
		notificationIcon: "@drawable/ic_background",
		wakeLockTime: 60*6,
		autoStop: false,
		interval: 2
	),
);
```
**notificationIcon: "@drawable/ic_background"** fixed the problem!

**Comment by moovida** [comment]
I am quite puzzeled, for me this worked having the notification icon done in asset studio and paced like this:

![image](https://user-images.githubusercontent.com/390250/80678317-f78d3c80-8aba-11ea-9516-a33f946eec9b.png)

and then just calling it like:

```
    var locationSettings = LocationSettings(
        notificationTitle: "SMASH location service is active.",
        notificationMsg: "",
        notificationIcon: "smash_notification",
        wakeLockTime: 20,
        autoStop: false,
        accuracy: smashLocationAccuracy.accuracy,
        interval: 1);
```

I have no other reference to smash_notification.png anywhere.

**Comment by sspatari** [comment]
I've solved it by setting it like in the images below
![image](https://user-images.githubusercontent.com/17746926/106946652-0bdd2480-6732-11eb-8f26-5831091e3918.png)
![image](https://user-images.githubusercontent.com/17746926/106946711-21eae500-6732-11eb-8a35-f1764c9e03d2.png)

**Comment by andrezanna** [comment]
> fml (I know, best start for a comment, but it took me hours to figure it out...)
> 
> **Problem:**
> I always got a white square as notification icon. My launch icon is a grey square with some text.
> 
> **What I tried:**
> 
> * I generated the required image-files with https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_ac_unit
>   
>   * my icon-name is ic_background
>   * because I selected an icon the subdirs are res/drawable-*
> * I copied the content of the downloaded zip-file to path_to_app_project/android/app/src/main
> * I added following to the application-tag in android/app/src/main/AndroidManifest.xml
> 
> ```
> <meta-data
>             android:name="com.google.firebase.messaging.default_notification_icon"
>             android:resource="@drawable/ic_background" />
> ```
> 
> * I tried: (**But I think it's wrong.** This file is for splash screens as its comments say. Therefore I **removed it afterwards**.)
> 
> > Hello.
> > Working now. The icons are ok. But i have to add a reference for them on **res/drawable/launch_background.xml**:
> > ```
> > <?xml version="1.0" encoding="utf-8"?>
> > 
> > <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
> > 	<item android:drawable="@android:color/white" />
> > 	
> > 	<item>
> > 		<bitmap android:gravity="center" android:src="@mipmap/ic_background" />
> > 	</item>
> > </layer-list>
> > ```
> 
> Nothing worked, still got the dammit white square 😡
> 
> **Solution:**
> I defined the icon in the LocationSettings:
> 
> ```js
> BackgroundLocator.registerLocationUpdate(
> 	callback,
> 	//optional
> 	androidNotificationCallback: notificationCallback,
> 	settings: LocationSettings(
> 		accuracy: LocationAccuracy.NAVIGATION,
> 		notificationTitle: "Awesome title",
> 		notificationMsg: "Event more awesome text",
> 		notificationIcon: "@drawable/ic_background",
> 		wakeLockTime: 60*6,
> 		autoStop: false,
> 		interval: 2
> 	),
> );
> ```
> 
> **notificationIcon: "@drawable/ic_background"** fixed the problem!

this solved my issue

**Comment by alwijein** [comment]
> Hello.
> 
> Working now. The icons are ok. But i have to add a reference for them on **res/drawable/launch_background.xml**:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> 
> <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
> 	<item android:drawable="@android:color/white" />
> 	
> 	<item>
> 		<bitmap android:gravity="center" android:src="@mipmap/ic_background" />
> 	</item>
> </layer-list>
> ```

this solve my issue
