### ISSUE TITLE
IOS: Does not ask for location permission.

### ISSUE THREAD

**Issue by wemersonrv** [rekab-app/background_locator#50]
Hello.

It's working fine on Android. But on iOS it not asks for permission and of course, not works.

See app permission... not have location permissions:

![image](https://user-images.githubusercontent.com/2028673/80365244-a9c7c880-885d-11ea-997a-bd7763e4c9cb.png)

Do i miss something???

Below my files as oriented in documentation:

**AppDelegate.swift**
```swift
import UIKit
import Flutter
import Firebase
import background_locator
import GoogleMaps

func registerPlugins(registry: FlutterPluginRegistry) -> () {
    GeneratedPluginRegistrant.register(with: registry)
}

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
    // Background Location BEGIN
    BackgroundLocatorPlugin.setPluginRegistrantCallback(registerPlugins)
    // Background Location END

    // Google MAPS BEGIN
    GMSServices.provideAPIKey("-----------------------")
    // Google MAPS END
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

**Info.plist**
```xml
		<!-- Background Location Settings BEGIN -->
		<key>
			NSLocationAlwaysAndWhenInUseUsageDescription
		</key>
		<string>
			Location Needed
		</string>
		<key>
			NSLocationAlwaysUsageDescription
		</key>
		<string>
			Location Needed
		</string>
		<key>
			NSLocationWhenInUseUsageDescription
		</key>
		<string>
			Location Needed
		</string>
		<key>
			UIBackgroundModes
		</key>
		<array>
			<string>
				location
			</string>
		</array>
		<!-- Background Location Settings BEGIN -->
```

**Runner settings**
![WhatsApp Image 2020-04-27 at 08 31 00](https://user-images.githubusercontent.com/2028673/80368373-04afee80-8863-11ea-8c3e-c29c20741d3f.jpeg)

**Comment by gpibarra** [comment]
The library does not ask for permissions. Permissions should be asked in the main app(for example package location_permissions/location_permissions. 
You did this?
[`https://github.com/rekab-app/background_locator/blob/86ef3a83714f9f2dc0e19f4fa711e39d6e2789f3/example/lib/main.dart#L174`](https://github.com/rekab-app/background_locator/blob/86ef3a83714f9f2dc0e19f4fa711e39d6e2789f3/example/lib/main.dart#L174)

**Comment by wemersonrv** [comment]
> The library does not ask for permissions. Permissions should be asked in the main app(for example package location_permissions/location_permissions.
> You did this?
> [`https://github.com/rekab-app/background_locator/blob/86ef3a83714f9f2dc0e19f4fa711e39d6e2789f3/example/lib/main.dart#L174`](https://github.com/rekab-app/background_locator/blob/86ef3a83714f9f2dc0e19f4fa711e39d6e2789f3/example/lib/main.dart#L174)

Yes i do. see my code:

```dart
@override
  Widget build(BuildContext context) {
    if (!isRunning && isBackgroundActive) {
      _checkLocationPermission();
    }

    return OKToast(
      duration: Duration(seconds: Helpers.toastDuration),
      position: ToastPosition.bottom,
      handleTouth: true,
      dismissOtherOnShow: true,
      child: Visibility(
        visible: (linkFetch == true),

        ...


  void _checkLocationPermission() async {
    final access = await LocationPermissions().checkPermissionStatus();
    switch (access) {
      case PermissionStatus.unknown:
      case PermissionStatus.denied:
      case PermissionStatus.restricted:
        final permission = await LocationPermissions().requestPermissions(
          permissionLevel: LocationPermissionLevel.locationAlways,
        );
        if (permission == PermissionStatus.granted) {
          _startLocator();
        } else {
          // show error
        }
        break;
      case PermissionStatus.granted:
        _startLocator();
        break;
    }
  }

  void _startLocator() {
    BackgroundLocator.registerLocationUpdate(
      LocationBackground.callback,
      androidNotificationCallback: LocationBackground.notificationCallback,
      settings: LocationSettings(
        notificationTitle: "My App",
        notificationMsg: "My App Title",
        notificationIcon: 'ic_background',
        wakeLockTime: 20,
        autoStop: false,
        interval: 60 * 5, // 5 minutes (300 secs)
      ),
    );
    setState(() {
      isRunning = true;
    });
  }
```

It works on android, and ask for permission... see:
![image](https://user-images.githubusercontent.com/2028673/80385408-6597f080-887c-11ea-816a-1e399371c765.png)

But in iOS do not ask for permission, and the location permission is missing in permission list in app detail. See here:

![image](https://user-images.githubusercontent.com/2028673/80365244-a9c7c880-885d-11ea-997a-bd7763e4c9cb.png)

**Comment by mehdok** [comment]
Did you followed the instruction for setting up on [iOS](https://github.com/rekab-app/background_locator/wiki/Setup#ios) ?

You have to add location permission in `Info.plist`

**Comment by wemersonrv** [comment]
> Did you followed the instruction for setting up on [iOS](https://github.com/rekab-app/background_locator/wiki/Setup#ios) ?
> 
> You have to add location permission in `Info.plist`

Yes i do!

When i opened this post i add the **Info.plist** portion that has backgrond location settings... I thing i do not miss any setting...

**Comment by gpibarra** [comment]
Did you try running exactly the "example" from this repository? The Info.plist configuration looks good, but maybe there is something that the configuration is different.
If you try the "example" and it requires the permissions, we discard that it is not a problem of the library, but some missing documentation for the correct configuration.

**Comment by wemersonrv** [comment]
Works the example and works... weird... will investigate if something is missing here on my project.

But, in the repo "example" project is causing the same problem of this issue https://github.com/rekab-app/background_locator/issues/55#issuecomment-623807882_

**Comment by gpibarra** [comment]
try with the previous version of the repo, maybe there is something in the configuration that is missing (in that case better the documentation). Then we go back to the latest version of the library and wait to solve the bug

**Comment by Matthuffy** [comment]
I have the same issue

**Comment by Matthuffy** [comment]
Aaaaah! It is the App Target!

NSLocationAlwaysUsageDescription is for IOS 10+ I had IOS 8 set and removing this fixed the issue. But then also changing my target fixed it also.

**Comment by mehdok** [comment]
I think this problem is fixed, so I'm closing this issue, but feel free to open it anytime;
