### ISSUE TITLE
[question] best practices

### ISSUE THREAD

**Issue by moovida** [rekab-app/background_locator#52]
I have some questions that I think might interest others. I would be happy to gather the answers and make them a documentation page in the wiki. Not sure if the issue format is the best for this, but I will try:

### what is the best practice to stop the background logging on IOS? 

On Android I am able to intercept the back button and unregister properly the location listener. What is usually done in IOS? Is there a difference between switching off the screen and pushing the home button? 

In an app that allows background logging you have to explicitly make a difference between switching it off and just sending it to back and work on something else in the meanwhile.

### is there a way to tell if the user has the gps switched on at all? 

In the current situation I initialize the logging but then am not sure if no point is coming because the GPS is off or because it doesn't have a fix. Is there a way to tell?

### notification dynamic  info

Is there a way to send notification updates. It is almost a pity to have the LocationSettings be static at first startup. It would be great to be able to send updates, let the user know the current accuracy and if the gps has a fix or when not.

### what is the best practice to change locationaccuracy?

Do I have to go through the whole 

```
    if (IsolateNameServer.lookupPortByName(_isolateName) != null) {
      IsolateNameServer.removePortNameMapping(_isolateName);
    }
    await GPS.BackgroundLocator.unRegisterLocationUpdate();
```

and restart from scratch? It is not much work, just wanted to know if this is the proper way.

Thanks for any insight.

**Comment by gpibarra** [comment]
for "notification dynamic info"
[https://github.com/rekab-app/background_locator/issues/53](https://github.com/rekab-app/background_locator/issues/53)

**Comment by mehdok** [comment]
Sorry for late answer.

> Is there a difference between switching off the screen and pushing the home button?

There is a bug in iOS #54 and right now I don't have any straight answer for your question.

> In the current situation I initialize the logging but then am not sure if no point is coming because the GPS is off or because it doesn't have a fix. Is there a way to tell?

Right now there is no way to tell the difference, But is would be a nice feature to add.

> ### what is the best practice to change locationaccuracy?
> Do I have to go through the whole
> 
> ```
>     if (IsolateNameServer.lookupPortByName(_isolateName) != null) {
>       IsolateNameServer.removePortNameMapping(_isolateName);
>     }
>     await GPS.BackgroundLocator.unRegisterLocationUpdate();
> ```
> 
> and restart from scratch? It is not much work, just wanted to know if this is the proper way.
> 

There is no need to re-register the `solateNameServer`. If your app is open and you need to change the accuracy just stop the plugin, init it with new accuracy setting and start it again.

**Comment by moovida** [comment]
Hi @mehdok, thanks for your reply. Is there a better way to help you out with the documentation, if I am to contribute some? I see the IOS Setup part is not yet up and I feel back, because you should not have the burden. Would it be possible to get write access to the wiki part, so that I could add the setup part and maybe start an FAQ page? Write access could also be just for a little while. The missing of pull requests for wikis makes it difficult to contribute docs without stressing you :-)

**Comment by mehdok** [comment]
@moovida Sorry for not adding your file into the wiki. I wanted to ask you add a separate part for iOS integration and I got stuck into my work and forgot that.

Please separate your walkthrough and add a separate section to wiki and then follow the steps in this [qa](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) or just email me your `.md` file and I will add it to wiki.

**Comment by moovida** [comment]
Hi @mehdok , maybe I gave the wrong impression, I just wanted to help and not stress. :-)

I will look at that wiki PR walkaround.

Just to be sure, you want me to extract the whole IOS setup part into a new page or just the one I added?

**Comment by mehdok** [comment]
Just the integration from objective-c to swift.
