### ISSUE TITLE
[Question/Feature request] Update/Change notification message

### ISSUE THREAD

**Issue by scotty86** [rekab-app/background_locator#53]
Hello,

is there a way to update the notification message?

Background: I want to track the distance someone has moved and it would be great, if I could show the current distance value in the notification.

Greetings
scotty86

**Comment by mehdok** [comment]
Currently there is no way to do such thing. But it's a nice feature and will be added someday :).

**Comment by mehdok** [comment]
This should be fixed by #125 ;
