### ISSUE TITLE
[Android]Notification Icon Not Working

### ISSUE THREAD

**Issue by khairu-aqsara** [rekab-app/background_locator#56]
LocationSettings options for notificationIcon not working when we change the icon, it's not visible as it should, just white rectangle when the app in production build `flutter build apk --split-per-abi` but it working when in development.

![WhatsApp Image 2020-05-04 at 22 25 17](https://user-images.githubusercontent.com/25432146/80983058-4f7ac900-8e56-11ea-9422-049b0636ad3b.jpeg)

the icon image was in mipmap(s) diretory with name tracking_enable.png 

```
      settings: LocationSettings(
        notificationIcon: 'tracking_enable',
        ....
     )
```

Tested With
Google Pixel 2 XL Android 10
Flutter 1.12.13+hotfix.9

**Comment by gpibarra** [comment]
It seems more like an android problem than a library problem.
see 
https://github.com/rekab-app/background_locator/issues/48

**Comment by wemersonrv** [comment]
> It seems more like an android problem than a library problem.
> see
> #48

Exactly! This is my issue and works amazing now!!

I have the same problema as you @khairu-aqsara and the solution is well-documented now.

I strongly recommend u to read the entire issue messages on recommendation that @gpibarra posted here.

**Comment by khairu-aqsara** [comment]
thankyou, 
it's working now using this #48
