### ISSUE TITLE
Turn Off Notification

### ISSUE THREAD

**Issue by worldbucks** [rekab-app/background_locator#58]
Just wondering is there a way to turn off notification?

**Comment by gpibarra** [comment]
No. On android, the library make a native service, and that service always has to have a stiky notification.

**Comment by yogiis98** [comment]
@gpibarra Can we change the notification text if GPS is off in callback mentioning that GPS is off.

**Comment by gpibarra** [comment]
For now only the text is set when starting service. You cannot dynamically change the notification text (for example when the GPS status is changed).
In futures versions this functionality will considered.
[https://github.com/rekab-app/background_locator/issues/53](https://github.com/rekab-app/background_locator/issues/53)

**Comment by mehdok** [comment]
@gpibarra provided the needed information. So I'm closing this issue for now, feel free to open it at anytime;
