### ISSUE TITLE
Passing parameter to callback function

### ISSUE THREAD

**Issue by miamir2000** [rekab-app/background_locator#60]
How to pass parameter to callback function, eg: username

**Comment by praveenbbhati** [comment]
Hi @miamir2000  Can you please explain what you want to achieve?

**Comment by miamir2000** [comment]
Hi praveenbbhati,

I would like to push username, latitude & longitude to cloud server inside callback function.
1. Try using global variable (static String username) - when I set value, it not reflect value inside callback function.
2. Try store value using shared preference & retrieve inside callback function, got exception error. 

Please advise, thank you in advance.

static void callback(LocationDto locationDto) async {
  // TODO: 
  sendLocation(username, locationDto.latitude, locationDto.longitude);
}

**Comment by gpibarra** [comment]
Service background run in an independent process, the static variables of the main process are not accessible from the background process (there are other instances of those same variables).
Try shared preferences. As for the exception, check the documentation: [https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback](https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback)

**Comment by mehdok** [comment]
@miamir2000 Do you still have problem or found a workaround?

**Comment by mehdok** [comment]
Closing this issue due inactivity.
