### ISSUE TITLE
Get vertical speed in callback

### ISSUE THREAD

**Issue by ludesert** [rekab-app/background_locator#61]
Hi,
I need to get the vertical speed during the callback.
For this, I need to have different altitudes at 2 different times to calculate the speed.

Is it possible to get a new location update IN the callback method ? I tried using this plugin to get a location update : https://github.com/Lyokone/flutterlocation/

But I can't register it, I get this error while starting the service : 

`E/AndroidRuntime(32274): java.lang.RuntimeException: Unable to create service rekab.app.background_locator.LocatorService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.app.Activity.getMainLooper()' on a null object reference
E/AndroidRuntime(32274): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4169)
E/AndroidRuntime(32274): 	at android.app.ActivityThread.access$2400(ActivityThread.java:273)
E/AndroidRuntime(32274): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055)
E/AndroidRuntime(32274): 	at android.os.Handler.dispatchMessage(Handler.java:112)
E/AndroidRuntime(32274): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(32274): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AndroidRuntime(32274): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32274): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(32274): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/AndroidRuntime(32274): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.app.Activity.getMainLooper()' on a null object reference
E/AndroidRuntime(32274): 	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:50)
E/AndroidRuntime(32274): 	at com.google.android.gms.location.FusedLocationProviderClient.<init>(Unknown Source:8)
E/AndroidRuntime(32274): 	at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source:2)
E/AndroidRuntime(32274): 	at com.lyokone.location.FlutterLocation.setActivity(FlutterLocation.java:106)
E/AndroidRuntime(32274): 	at com.lyokone.location.LocationPlugin.registerWith(LocationPlugin.java:35)
E/AndroidRuntime(32274): 	at com.ludesert.autologbook.Application.registerWith(Application.kt:23)
E/AndroidRuntime(32274): 	at rekab.app.background_locator.LocatorService.startLocatorService(LocatorService.kt:90)
E/AndroidRuntime(32274): 	at rekab.app.background_locator.LocatorService.onCreate(LocatorService.kt:63)
E/AndroidRuntime(32274): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4150)
E/AndroidRuntime(32274): 	... 8 more
I/Process (32274): Sending signal. PID: 32274 SIG: 9
Lost connection to device.`

Any idea ? Thanks

**Comment by gpibarra** [comment]
For register other plugins, check the documentation: [https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback](https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback)

**Comment by ludesert** [comment]
I know, and it did not work with flutterlocation.
I tried with this plugin : https://pub.dev/packages/geolocator and it works perfectly.
