### ISSUE TITLE
Service killed by Android

### ISSUE THREAD

**Issue by ludesert** [rekab-app/background_locator#62]
I have a start and stop button in my app to register or unregister the background service. It works like a charm even when the app is killed (that's the intent of the plug-in), but for some reasons, after 10-15 min the notification disappears. 

Is the service sticky? Because I guess it should start again everytime it gets killed, right? 

I'm using a Huawei honor 10.

**Comment by mehdok** [comment]
The service is sticky and the whole purpose of the notification is to keep the service alive. It would be a great help if you can provide more information, code or logs;

**Comment by ludesert** [comment]
I think the problem is ... Huawei !
Their OS ignores Android's battery optimization settings and kills the background service if the app is not manually whitelisted in the phone settings. I haven't found any solution to avoid this problem on Huawei devices.

The service worked perfectly on a Samsung device.

**Comment by mehdok** [comment]
This could be Huawei, But I can see some battery apps keep their service alive on Huawei. I'm looking into it;

**Comment by ludesert** [comment]
After what I've read, it seems to be a problem on most Chinese phones ... I haven't found a solution yet.

**Comment by mehdok** [comment]
I couldn't find any solution for Huawei phones, so I'm closing this issue, but feel free to open it anytime;
