### ISSUE TITLE
object-c and faq wiki pages

### ISSUE THREAD

**Issue by moovida** [rekab-app/background_locator#64]
Sorry this took long and is not using the pull request workaround @mehdok , but the risk is that I never submit it. :-/

As discussed in issue #52 please find attached the object-c setup page as a single page.

I also started an FAQ page with some questions I asked. I think in general it might be a good addition to the wiki and help to answer some of the issues that get opened regularly. Feel free to do whatever with it :-)

[wiki_pages.zip](https://github.com/rekab-app/background_locator/files/4660836/wiki_pages.zip)

**Comment by mehdok** [comment]
Thanks man, It was a great help;
