### ISSUE TITLE
Bad state: Stream has already been listened to

### ISSUE THREAD

**Issue by sgalway00** [rekab-app/background_locator#70]
I have successfully implemented your package but when I try to start the isolate a second time I get an error "Bad state: Stream has already been listened to."  During the first activation everything works as expected.

```
static void callback(LocationDto locationDto) async {
    print('location in dart: ${locationDto.toString()}');

    final SendPort send = IsolateNameServer.lookupPortByName(_gpsIsolate);
    send?.send(locationDto);
  }

  void getLocationFromBackground(LocationDto inGpsData) async {
    print(inGpsData);
  }

  void startLocationService() {
    print('startLocationService started');
    BackgroundLocator.registerLocationUpdate(
      callback,
      //optional
      //androidNotificationCallback: notificationCallback,
      settings: LocationSettings(
          //Scroll down to see the different options
          notificationTitle: "Start Location Tracking example",
          notificationMsg: "Track location in background exapmle",
          wakeLockTime: 20,
          autoStop: false,
          interval: 1),
    );
  }

  void startGps2() async {
    print('startGps2 pressed');

    if (IsolateNameServer.lookupPortByName(_gpsIsolate) != null) {
      IsolateNameServer.removePortNameMapping(_gpsIsolate);
    }

     IsolateNameServer.registerPortWithName(
        gpsReceivePort.sendPort, _gpsIsolate);

     startLocationService();

    

     gpsReceivePort.listen((dynamic data) async {
      getLocationFromBackground(data);
      print('Incoming Data: $data');
    });
  }

  void stopGps2() async {
    BackgroundLocator.unRegisterLocationUpdate();
    IsolateNameServer.removePortNameMapping(_gpsIsolate);

    gpsReceivePort.close();

    print('stopGps2 pressed, Isolate stopped');

    
  }
```
`VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Bad state: Stream has already been listened to.
#0      _StreamController._subscribe  (dart:async/stream_controller.dart:683:7)
#1      _ControllerStream._createSubscription  (dart:async/stream_controller.dart:833:19)
#2      _StreamImpl.listen  (dart:async/stream_impl.dart:475:9)
#3      _ReceivePortImpl.listen  (dart:isolate-patch/isolate_patch.dart:87:31)
#4      GPSBloc.startGps2 
package:yonav2/blocs/gpsBloc.dart:161
#5      _GpsSwitchState.build.<anonymous closure>.<anonymous closure> 
package:yonav2/gpsWidgets/gpsWidgets.dart:62
#6      _rootRunUnary  (dart:async/zone.dart:1192:38)
#7      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
#8      _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
#9      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:682:45)
#10     Future._propagateToListeners  (dart:async/future_impl.dart:711:32)
#11     Future._completeWithValue (dart:async/future_impl.da<…>`

**Comment by leonardoayres** [comment]
Have you tried to close the Port and recreate it?

Move the:
`gpsReceivePort.listen((dynamic data) async {
      getLocationFromBackground(data);
      print('Incoming Data: $data');
    });`

to a function and call it to recreate the Port.

**Comment by sgalway00** [comment]
From my code snippet above you can see that I do close the port in the stopGps2() function.

I don't understand what you mean my "move to a function".  The listener should be in a separate function from where the port is created?

**Comment by leonardoayres** [comment]
@sgalway00 you could do something like that:

void _backgroundListener() {
    if (gpsReceivePort != null) {
    --- your code ---
    } else {
    --- create the port ---
   }
}

But my scenario is that i'm only activate the background_locator when my app go to INACTIVE state, so i have to create and recreate the port in certains conditions.

**Comment by mehdok** [comment]
Closing this issue due inactivity, but feel free to open it anytime;
