### ISSUE TITLE
No static method isAtLeastR()Z

### ISSUE THREAD

**Issue by merlinko637** [rekab-app/background_locator#72]
Hello, when importing your plugin, using embedding v2 and using android API v29 i get the following error (it is when plugin gets registered):

java.lang.NoSuchMethodError: No static method isAtLeastR()Z in class Landroidx/core/os/BuildCompat; or its super classes (declaration of 'androidx.core.os.BuildCompat' appears in ...

I found that, it is necessary to update this package to latest version:
com.google.android.gms:play-services-base@@17.2.1:21

according to this article:
https://stackoverflow.com/questions/60812702/java-lang-nosuchmethoderror-no-static-method-isatleastrz

Could you please do so, because otherwise I have no idea how to make it work :/

Thanks in advance

**Comment by mehdok** [comment]
@merlinko637 I didn't use this package in the plugin. Please add it to your app and let me know if it fixed the problem;

**Comment by merlinko637** [comment]
@mehdok i guess i wasnt exact. I think the ...play-services-location uses this package which is in version 17.0.0

**Comment by merlinko637** [comment]
Okay my mistake :/ i found that location 17.0.0 uses base 17.2.1 which is good

https://mvnrepository.com/artifact/com.google.android.gms/play-services-location/17.0.0

But now i have absolutely no idea what is causing my error :/

**Comment by mehdok** [comment]
Does your project supports `AndroidX` ?

**Comment by merlinko637** [comment]
Yes I have android.useAndroidX=true in my gradle.properties

**Comment by merlinko637** [comment]
I found out that the problem was on my end and I think it was really specific. Package com.google.android.gms:play-services-base was trying to use a function that was not present in my BuildCompat class (i think i did not have newest version but didnt figure out how to update it - or maybe when resolving, older version was chosen), so i used this in build.gradle and everything is working now (this package is not trying to use that function that was not present)

resolutionStrategy.force 'com.google.android.gms:play-services-base:17.1.0'

**Comment by mehdok** [comment]
@merlinko637 Glad to hear that problem solved. It would be nice if you could prepare a problem and solution for `FAQ` section. maybe it helps someone else;
