### ISSUE TITLE
Permission Request

### ISSUE THREAD

**Issue by gpibarra** [rekab-app/background_locator#8]
In the beta version, on start app request permissions.
In version 1.0.0 + 1 does not request permissions.
This is correct? In that case you have to change the "example" using any library (https://pub.dev/packages/permission_handler for example) to manage it.

To make it go, 
Run app the first time
Click "start" button. 
Show error "[ERROR: flutter / lib / ui / ui_dart_state.cc (157)] Unhandled Exception: PlatformException ('registerLocator' requires the ACCESS_FINE_LOCATION permission., Null, null)".
Leave app, and go to app's information, and give it permissions manually.
Open app again and it work ok.

**Comment by mehdok** [comment]
You are right, I was in a hurry and forgot to update the example.
From this version the plugin doesn't handle the permission.
