### ISSUE TITLE
 I am unable to update the Firestore Database values in the 'callback' function of this plugin

### ISSUE THREAD

**Issue by chollarasan** [rekab-app/background_locator#80]
@mehdok I am unable to post the values to the firebase. in the 'callback' method

**Comment by chollarasan** [comment]
@mehdok I am unable to post the values to the firebase

**Comment by mehdok** [comment]
Did you followed the steps in the [Use other plugins in callback](https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback) ?

**Comment by chollarasan** [comment]
ya it is working now
