### ISSUE TITLE
Shared prefs : different instances ?

### ISSUE THREAD

**Issue by ludesert** [rekab-app/background_locator#92]
I've been having some issues with my app and decided to try every step of my callback function in a different, simple app with a start and stop button.

I found something very strange  while using the SharedPreferences plugin 

As an example, if I set the value of an int in sharedPrefs called 'test' to 0 while pressing the start button, before starting the background locator service, and then print it with the callback function, it works. If I increment the value of 'test' each time the callback is called, it works.

When I stop the background location service with the stop button (this step works), and then start it again with the start button, this int should be reset to 0. But it's not the case since the callback function continues to increment the value 'test' had before the service was stopped ... What am I doing wrong ?

EDIT : it seems that the sharedPrefs variables are updated for the callback function and NOT for the app, unless I perform a hot restart ...

Here is the code of the app (sorry I don't know how to make it look normal ... : 
```dart

import 'package:background_locator/background_locator.dart';
import 'package:background_locator/location_dto.dart';
import 'package:background_locator/location_settings.dart';
import 'package:flutter/material.dart';

import 'package:location_permissions/location_permissions.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:isolate';
import 'dart:ui';




void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

// ignore: must_be_immutable
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;


  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool stopPressed = true;

  static const String _isolateName = "LocatorIsolate";
  ReceivePort port = ReceivePort();
  bool isRunning;
  LocationDto lastLocation;

  void initState() {
    super.initState();
    IsolateNameServer.registerPortWithName(port.sendPort, _isolateName);
    port.listen((dynamic data) {
      // do something with data
    });
    initPlatformState();
  }

  Future<void> initPlatformState() async {

    await BackgroundLocator.initialize();
    //print('Initialization done');
    final _isRunning = await BackgroundLocator.isRegisterLocationUpdate();
    setState(() {
      isRunning = _isRunning;
    });
    //print('Running ${isRunning.toString()}');

    if(stopPressed){
      // Stop background location service
      BackgroundLocator.unRegisterLocationUpdate();
      setState(() {
        isRunning = false;
      });
    }
    else if (!isRunning){
      // Start background location service if it's not running but the STOP button is not pressed
      _checkLocationPermission();
    }
  }


  static void callback(LocationDto locationDto) async {
    //print('callback called');
    //print(DateTime.now());

    final SendPort send = IsolateNameServer.lookupPortByName(_isolateName);
    send?.send(locationDto);
    //print(_isolateName);


    final SharedPreferences prefs = await SharedPreferences.getInstance();


    print(prefs.getInt('test'));
    prefs.setInt('test', prefs.getInt('test')+1);

  }




  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: [
          Row(
            children: <Widget>[
              Container(
                margin: const EdgeInsets.only(right: 42),
                child: RaisedButton(
                  child: const Text("Start"),
                  onPressed: !stopPressed ? null : () async {

                    // set button state
                    setState(() {
                      stopPressed = false;
                    });

                    final SharedPreferences prefs = await SharedPreferences.getInstance();
                    prefs.clear();


                    print(prefs.getInt('test'));

                    print('reset');
                    prefs.setInt('test', 0);
                    print(prefs.getInt('test'));



                    await Future.delayed(Duration(seconds: 3));


                    // Start background location service
                    _checkLocationPermission();

                    // Confirmation popup
                    return showDialog(
                        context: context,
                        barrierDismissible: true, // user must tap button for close dialog!
                        builder: (BuildContext context) {
                          return AlertDialog(
                              title: Text('Started...'),
                              content: Text(
                                  "Started"),
                              actions: <Widget>[
                                FlatButton(
                                  onPressed: () => Navigator.of(context).pop(),
                                  child: Text('Ok'),
                                ),
                              ]
                          );
                        }
                    );
                  },
                ),
              ),//start
              RaisedButton(
                  child: const Text('Stop'),
                  onPressed: stopPressed ? null : () async {

                    // Set state
                    setState(() {
                      stopPressed = true;
                    });

                    // stop background location service
                    BackgroundLocator.unRegisterLocationUpdate();
                    },
              ),//stop
            ],
          ),
        ],
      ),
    );
  }


  void _checkLocationPermission() async {
    final access = await LocationPermissions().checkPermissionStatus();
    switch (access) {
      case PermissionStatus.unknown:
      case PermissionStatus.denied:
      case PermissionStatus.restricted:
        final permission = await LocationPermissions().requestPermissions(
          permissionLevel: LocationPermissionLevel.locationAlways,
        );
        if (permission == PermissionStatus.granted) {
          _startLocator();
        } else {
          return showDialog(
              context: context,
              barrierDismissible: true, // user must tap button for close dialog!
              builder: (BuildContext context) {
                return AlertDialog(
                    title: Text('Error !'),
                    content: Text(
                        "Error"),
                    actions: <Widget>[
                      FlatButton(
                        onPressed: () => Navigator.of(context).pop(),
                        child: Text('Ok'),
                      ),
                    ]
                );
              }
          );
        }
        break;
      case PermissionStatus.granted:
        _startLocator();
        break;
    }
  }

  void _startLocator() {
    BackgroundLocator.registerLocationUpdate(
      callback,
      settings: LocationSettings(
        notificationTitle: "..",
        notificationMsg: "Msg.",
        wakeLockTime: 1200,
        autoStop: false,
        interval: 1,
        distanceFilter: 0,
        accuracy: LocationAccuracy.NAVIGATION,
      ),
    );
  }


}
```

**Comment by gpibarra** [comment]
Look at the currentversion in master, and the example. Use "cabackInit".

**Comment by ludesert** [comment]
Oh I haven't seen this new functionality since it was added.

But I don't really understand how to use it ...

**Comment by sairaj83** [comment]
I used below code in Application.kt for using sharedPreferences in back ground locator.


import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin
import io.flutter.view.FlutterMain
import rekab.app.background_locator.LocatorService

class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        LocatorService.setPluginRegistrant(this)
        FlutterMain.startInitialization(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin("plugins.flutter.io/shared_preferences")) {
            SharedPreferencesPlugin.registerWith(registry!!.registrarFor("plugins.flutter.io/shared_preferences"))
        }
    }
}

**Comment by ludesert** [comment]
That's what I did too, I still have this problem of '' different instances '' of the plug-in...

**Comment by sairaj83** [comment]
> That's what I did too, I still have this problem of '' different instances '' of the plug-in... 



Show the  application.kt code please or post the error your are getting

**Comment by ludesert** [comment]
I don't get any error code. Here is my application.kt code : 

`package com.ludesert.trackingtest

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.view.FlutterMain
import io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin
import rekab.app.background_locator.LocatorService
import com.baseflow.geolocator.GeolocatorPlugin
import com.baseflow.location_permissions.LocationPermissionsPlugin
import com.baseflow.googleapiavailability.GoogleApiAvailabilityPlugin


class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        LocatorService.setPluginRegistrant(this)
        FlutterMain.startInitialization(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        if (!registry!!.hasPlugin("io.flutter.plugins.shared_preferences")) {
            SharedPreferencesPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.shared_preferences"))
        }
        if (!registry!!.hasPlugin("com.baseflow.geolocator")) {
            GeolocatorPlugin.registerWith(registry!!.registrarFor("com.baseflow.geolocator"))
        }
        if (!registry!!.hasPlugin("com.baseflow.location_permissions")) {
            LocationPermissionsPlugin.registerWith(registry!!.registrarFor("com.baseflow.location_permissions"))
        }
        if (!registry!!.hasPlugin("com.baseflow.google_api_availability")) {
            GoogleApiAvailabilityPlugin.registerWith(registry!!.registrarFor("com.baseflow.google_api_availability"))
        }
    }
}
`

**Comment by sairaj83** [comment]
change 

 'if (!registry!!.hasPlugin("io.flutter.plugins.shared_preferences")) {
            SharedPreferencesPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.shared_preferences"))
        }'

to

 if (!registry!!.hasPlugin("plugins.flutter.io/shared_preferences")) {
        SharedPreferencesPlugin.registerWith(registry!!.registrarFor("plugins.flutter.io/shared_preferences"))
    }

**Comment by mehdok** [comment]
@sairaj83 I don't think that the problem is related to package name, the `SharedPreferences` plugin is working for him, but not in the way that expected.

**Comment by ludesert** [comment]
@sairaj83 I'll try this tomorrow, but I think @mehdok is right because the plugin is working for me.

**Comment by mehdok** [comment]
@ludesert I Believe the key point here is **`await sharedPreferences.reload();`**. I just created simple example and everything worked fine. my callback is a global ruction like this:
 
```dart
Future<void> locationCallback(LocationDto location) async {
    final sharedPreferences = await SharedPreferences.getInstance();
    await sharedPreferences.reload();
    final preferencesManager = PreferencesManager(sharedPreferences);
    print('locationCallback: ${preferencesManager.getNumber()}');
  }
```

**Comment by ludesert** [comment]
> @ludesert I Believe the key point here is **`await sharedPreferences.reload();`**. I just created simple example and everything worked fine. my callback is a global function like this:
> 
> ```dart
> Future<void> locationCallback(LocationDto location) async {
>     final sharedPreferences = await SharedPreferences.getInstance();
>     await sharedPreferences.reload();
>     final preferencesManager = PreferencesManager(sharedPreferences);
>     print('locationCallback: ${preferencesManager.getNumber()}');
>   }
> ```

@mehdok was right : I did not reload the shared prefs. Now it works as expected. Thank you!
