### ISSUE TITLE
[Question] I want to ask can i use Provider package instead of isolaote

### ISSUE THREAD

**Issue by heinzan** [rekab-app/background_locator#93]
I want to use with provide.So can i use provider instead of isolate.That can make more clean and maintainable.Who did it?

**Comment by mehdok** [comment]
What is the `Provider` you are referring to? It would be nice if you provide a like to that so I can investigate more.

**Comment by heinzan** [comment]
I mean Provider package one of state management.

**Comment by ElZombieIsra** [comment]
Provider is used for state management. Isolate is used to run dart code in another thread besides the main one so you can't replace the Isolate one. But you can use it in conjunction with Provider although I don't know how or why would you do this.

**Comment by mehdok** [comment]
I'm closing this issue to due inactivity, but feel free to open it anytime;
