### ISSUE TITLE
Callback function not finishing ?

### ISSUE THREAD

**Issue by ludesert** [rekab-app/background_locator#95]
I need to use more than 1 GPS position in my callback function, so I use the geolocation plugin. I've had some problems and decided to make a simple tracking app to compare the position returned by this plugin and the bacground_locator, during a 1 hour drive.

Surprise : while the track is complete with the location returned by the background_locator (LocationDto), the one generated with geolocator positions is not complete. So it seems that the callback functions does not work every time it's called ... See the pics.

With background_locator plugin
[https://i.imgur.com/VlKdj7u.png](url)

With geolocation plugin
[https://i.imgur.com/EWY9gm3.png](url)

Could it be possible to add a function that enables you to get a new location update directly frop background_locator plugin while IN the callback function ? I need this to calculate the vertical speed of the device as an example (using the altitude information).

Thanks

**Comment by gpibarra** [comment]
why do you need 2 gps?
Speed property is in LocationDTO. 
Properties are compatilbes between "background_locator" and "geolocator" plugins

LocationDto
[https://github.com/rekab-app/background_locator/blob/master/lib/location_dto.dart](https://github.com/rekab-app/background_locator/blob/master/lib/location_dto.dart)
Position
[https://github.com/Baseflow/flutter-geolocator/blob/develop/lib/models/position.dart](https://github.com/Baseflow/flutter-geolocator/blob/develop/lib/models/position.dart)

In any case, check the example
[https://github.com/rekab-app/background_locator/tree/master/example](https://github.com/rekab-app/background_locator/tree/master/example)
Compare current position with last position strored in static variable inside class location_service_repository or inside SharedPreferences plugin.

**Comment by ludesert** [comment]
I need to get the vertical speed, which is not available in any of this plugins. So I just calculate it with the difference of altitude between 2 positions separated by 1 or 2 seconds (depending on what I need).

In addition, my callback function needs to check the speed more than once : as an example, if the speed is below 20 m/s, I check again 10 seconds later to see if it has increased of decreased because my app depends on this kind of speed variation.

**Comment by ludesert** [comment]
Any idea ?

**Comment by ludesert** [comment]
Up ..

**Comment by mehdok** [comment]
Can you show some code? specially your callback function;

**Comment by ludesert** [comment]
I made a quick ''export via email'' button to be able to read the data I get. I made more tests and my conclusion is that the callback function is completed every time but for some reasons, there is a sort of pause between the beginning of the function (when I save the DTO location in sharedprefs) and the end (when I save the geolocator location).

The result is that there is a high number of functions that are pending and get executed randomly at the same time : I can get 15x the exact same position with geolocator while the locationDTO one will be updated. That causes a sort of accumulation of positions at the same place, which causes the strange track I showed you above.

So I don't understand why but background_locator seems not to be able to use geolocator plugin every time. But I need it (or an other one) to be able to calculate the instant vertical speed during the callback function ...


Here is the full code of the app : 

`import 'package:background_locator/background_locator.dart';
import 'package:background_locator/location_dto.dart';
import 'package:background_locator/location_settings.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:geolocator/geolocator.dart' as geo;
import 'package:location/location.dart' as location;
import 'package:location_permissions/location_permissions.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:isolate';
import 'dart:ui';

import 'package:url_launcher/url_launcher.dart';



void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

// ignore: must_be_immutable
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;


  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool stopPressed = true;

  static const String _isolateName = "LocatorIsolate";
  ReceivePort port = ReceivePort();
  bool isRunning;
  LocationDto lastLocation;

  void initState() {
    super.initState();
    IsolateNameServer.registerPortWithName(port.sendPort, _isolateName);
    port.listen((dynamic data) {
      // do something with data
    });
    initPlatformState();
  }

  Future<void> initPlatformState() async {

    await BackgroundLocator.initialize();
    //print('Initialization done');
    final _isRunning = await BackgroundLocator.isRegisterLocationUpdate();
    setState(() {
      isRunning = _isRunning;
    });
    //print('Running ${isRunning.toString()}');

    if(stopPressed){
      // Stop background location service
      BackgroundLocator.unRegisterLocationUpdate();
      setState(() {
        isRunning = false;
      });
    }
    else if (!isRunning){
      // Start background location service if it's not running but the STOP button is not pressed
      _checkLocationPermission();
    }
  }

  static Future<void> initCallback(Map<dynamic, dynamic> params) async {
    LocationServiceRepository myLocationCallbackRepository =
    LocationServiceRepository();
    await myLocationCallbackRepository.init(params);
  }


  static void callback(LocationDto locationDto) async {
    //print('callback called');
    //print(DateTime.now());

    final SendPort send = IsolateNameServer.lookupPortByName(_isolateName);
    send?.send(locationDto);
    //print(_isolateName);

    geo.Position position = await getPosition();

    final SharedPreferences prefs = await SharedPreferences.getInstance();

    String geoString = prefs.getString('geo');
    String dtoString = prefs.getString('dto');

    if (geoString == null || dtoString == null){
      prefs.setString('geo', '0;');
      prefs.setString('dto', '0;');
    }

    geoString = geoString + position.toString() + ';';
    dtoString = dtoString + 'Lat: ${locationDto.latitude}, Long: ${locationDto.longitude}' + ';';

    prefs.setString('geo', geoString);
    prefs.setString('dto', dtoString);
  }


  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children: [
          Row(
            children: <Widget>[
              Container(
                margin: const EdgeInsets.only(right: 42),
                child: RaisedButton(
                  child: const Text("Démarrer l'enregistrement"),
                  onPressed: !stopPressed ? null : () async {

                    // set button state
                    setState(() {
                      stopPressed = false;
                    });

                    final SharedPreferences prefs = await SharedPreferences.getInstance();

                    prefs.clear();

                    prefs.setString('geo', '0;');
                    prefs.setString('dto', '0;');

                    await Future.delayed(Duration(seconds: 3));

                    await requestLocationServicesActivation();

                    // Start background location service
                    _checkLocationPermission();

                    // Confirmation popup
                    return showDialog(
                        context: context,
                        barrierDismissible: true, // user must tap button for close dialog!
                        builder: (BuildContext context) {
                          return AlertDialog(
                              title: Text('Enregistrement en cours ...'),
                              content: Text(
                                  "Le service a bien démarré, vos heures de vol vont être enregistrées. \n\n"
                                      "Pour arrêter le service, revenez à cet écran puis cliquer sur 'arrêter'."),
                              actions: <Widget>[
                                FlatButton(
                                  onPressed: () => Navigator.of(context).pop(),
                                  child: Text('Ok'),
                                ),
                              ]
                          );
                        }
                    );
                  },
                ),
              ),//start
              RaisedButton(
                  child: const Text('Arrêter'),
                  onPressed: stopPressed ? null : () async {

                    // Set state
                    setState(() {
                      stopPressed = true;
                    });

                    // stop background location service
                    BackgroundLocator.unRegisterLocationUpdate();
                    },
              ),//stop
            ],
          ),
          RaisedButton(
            child: Text('send positions via email'),
            onPressed: () async {
              final SharedPreferences prefs = await SharedPreferences.getInstance();
              String geoString = prefs.getString('geo');
              String dtoString = prefs.getString('dto');

              try {
                launch('mailto:mail@gmail.com?body=//DTO $dtoString //GEO $geoString');
              } catch (e) {}

            },
          )
        ],
      ),
    );
  }


  void _checkLocationPermission() async {
    final access = await LocationPermissions().checkPermissionStatus();
    switch (access) {
      case PermissionStatus.unknown:
      case PermissionStatus.denied:
      case PermissionStatus.restricted:
        final permission = await LocationPermissions().requestPermissions(
          permissionLevel: LocationPermissionLevel.locationAlways,
        );
        if (permission == PermissionStatus.granted) {
          _startLocator();
        } else {
          return showDialog(
              context: context,
              barrierDismissible: true, // user must tap button for close dialog!
              builder: (BuildContext context) {
                return AlertDialog(
                    title: Text('Erreur !'),
                    content: Text(
                        "Le service n'a pas pu démarrer : l'application n'a pas accès à vos données de localisation.\n\n"
                            "Veuillez autoriser l'accès permanent aux données de localisation via les réglages de votre appareil."),
                    actions: <Widget>[
                      FlatButton(
                        onPressed: () => Navigator.of(context).pop(),
                        child: Text('Ok'),
                      ),
                    ]
                );
              }
          );
        }
        break;
      case PermissionStatus.granted:
        _startLocator();
        break;
    }
  }

  void _startLocator() {
    BackgroundLocator.registerLocationUpdate(
      callback,
      initCallback: ,
      settings: LocationSettings(
        notificationTitle: "Tracking en cours ...",
        notificationMsg: "Touchez pour revenir.",
        wakeLockTime: 1200,
        autoStop: false,
        interval: 5,
        distanceFilter: 0,
        accuracy: LocationAccuracy.NAVIGATION,
      ),
    );
  }


}

Future<void> requestLocationServicesActivation () async {
  if (!await geo.Geolocator().isLocationServiceEnabled()) {
    await location.Location().requestService();
  }
}

Future<geo.Position> getPosition() async {
  // Returns a PositionData item

  geo.Geolocator geolocator = geo.Geolocator();
  geo.Position _position;

  String _error;
  _error = null;

  try {
    final geo.Position _positionResult = await geolocator.getCurrentPosition(desiredAccuracy: geo.LocationAccuracy.best);
    _position = _positionResult;
  } on PlatformException catch (err) {
    _error = err.code;
  }
  return _error ?? _position;
}


Future<void> requestLocationPermission () async {
  //request always
  await LocationPermissions().requestPermissions(permissionLevel: LocationPermissionLevel.locationAlways);
}

class LocationServiceRepository {
  static LocationServiceRepository _instance = LocationServiceRepository._();

  LocationServiceRepository._();

  factory LocationServiceRepository() {
    return _instance;
  }

  static const String isolateName = 'LocatorIsolate';

  int _count = -1;

  Future<void> init(Map<dynamic, dynamic> params) async {
    print("***********Init callback handler");
    if (params.containsKey('countInit')) {
      dynamic tmpCount = params['countInit'];
      if (tmpCount is double) {
        _count = tmpCount.toInt();
      } else if (tmpCount is String) {
        _count = int.parse(tmpCount);
      } else if (tmpCount is int) {
        _count = tmpCount;
      } else {
        _count = -2;
      }
    } else {
      _count = 0;
    }
    print("$_count");
    final SendPort send = IsolateNameServer.lookupPortByName(isolateName);
    send?.send(null);
  }
}
`

**Comment by mehdok** [comment]
I think your assumption is right, I can see that you have 5 second interval for receiving locations, and I think `Geolocator` can not find a GPS fix in 5 second. You can set some logs to make sure this is the case, if this is the case the maybe setting larger intervals can fix the problem, or just set a flag to indicate if `Geolocator` is done with finding location then continue;

**Comment by ludesert** [comment]
I will try this as soon as possible, but I have been able to use Geolocator during smaller intervals (1 second between 2 fixes to get the vertical speed as an example) and it worked well. But this was not inside the callback function.

**Comment by mehdok** [comment]
It's just a gussying and there is no harm to test.

I'm not sure if what I'm going to say is related to your case or not, but it worth mentioning:
Using the callback function is a little tricky, suppose you have this code:

```dart
int testVar = 8;

void callback() {
   print('testVar is: $testVar');
}
```

in this case when you start the plugin, in each interval you can see `testVar is 8` in the console. 
After that you decide to change that variable, for example `testVar = 15;`, the expected behavior is that in the next interval callback should print `testVar is 15`, But the actual result is `testVar is 8`.

**Comment by mehdok** [comment]
I'm closing the issue due to inactivity, but feel free to open it anytime;
