### ISSUE TITLE
IOS-13 BUG - Location service does start until "always use" location permission is manually granted

### ISSUE THREAD

**Issue by dacianf** [rekab-app/background_locator#98]
On the last version "1.1.10+1", the plugin does not try anymore to get the location until "always use" location permission is granted so the os will no longer automatically request the always use permission.
If the "always use" permission is manually granted it will work as expected.

**Comment by mehdok** [comment]
Yesterday I saw it and I thought it's a glitch in my phone:) thanks for reporting, I'll check it soon;

**Comment by mehdok** [comment]
It should be fixed by #124 ;
